import type { Dream } from './types';

export const ANIMAL_DREAMS_3: Dream[] = [
  {
    slug: 'elephant', category: 'animal', tone: 'good', emoji: '🐘',
    ko: {
      name: '코끼리 꿈', keywords: ['코끼리', '흰 코끼리', '코끼리 꿈', '태몽'],
      summary: '코끼리는 큰 힘과 든든한 후원, 큰 재물을 뜻하는 길몽입니다. 흰 코끼리는 귀한 자녀를 얻는 태몽으로 유명합니다.',
      korea: '석가모니의 어머니가 흰 코끼리가 품에 드는 꿈을 꾸고 태어났다는 이야기 때문에, 흰 코끼리 꿈은 귀하게 될 자녀를 얻는 태몽으로 꼽힙니다. 코끼리를 타면 큰 후원자를 얻거나 높은 자리에 오르고, 코끼리가 집에 들어오면 큰 재물이 들어온다고 봅니다.',
      vietnam: '베트남에서 코끼리(voi)는 떠이응우옌(Tây Nguyên) 고원과 하이바쯩 자매의 전설처럼 힘과 위엄, 충성의 상징입니다. 코끼리 꿈은 든든한 지원과 행운, 큰 성공을 뜻합니다.',
      cases: [
        ['흰 코끼리가 품에 드는 꿈', '귀한 자녀를 얻는 대표적인 태몽입니다.'],
        ['코끼리를 타는 꿈', '큰 후원자를 얻거나 높은 자리에 오릅니다.'],
        ['코끼리가 집에 들어오는 꿈', '큰 재물과 복이 들어옵니다.'],
        ['코끼리가 날뛰는 꿈', '감당하기 큰 일이 생길 수 있으니 무리하지 마세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy voi', keywords: ['voi', 'voi trắng', 'cưỡi voi', 'nằm mơ thấy voi'],
      summary: 'Voi là điềm lành về sức mạnh, sự nâng đỡ vững chắc và tài lộc lớn. Voi trắng là giấc mơ báo sinh con quý.',
      korea: 'Theo tích Phật, mẹ của Đức Phật mơ thấy voi trắng vào lòng rồi sinh ra Ngài, nên người Hàn xem mơ voi trắng là giấc mơ báo có con quý. Cưỡi voi là được người có thế giúp đỡ, lên vị trí cao; voi vào nhà là tài lộc lớn.',
      vietnam: 'Với người Việt, voi gắn với Tây Nguyên và truyền thuyết Hai Bà Trưng cưỡi voi ra trận — biểu tượng sức mạnh, uy nghi và lòng trung thành. Mơ thấy voi là được hỗ trợ, may mắn, thành công lớn.',
      cases: [
        ['Mơ voi trắng vào lòng', 'Giấc mơ báo có con quý.'],
        ['Mơ cưỡi voi', 'Có quý nhân nâng đỡ, lên vị trí cao.'],
        ['Mơ voi vào nhà', 'Tài lộc và phúc lớn.'],
        ['Mơ voi nổi giận', 'Có việc quá sức — đừng gắng gượng.'],
      ],
    },
  },
  {
    slug: 'sheep', category: 'animal', tone: 'good', emoji: '🐑',
    ko: {
      name: '양·염소 꿈', keywords: ['양', '염소', '양떼', '양 꿈'],
      summary: '양은 온순함과 평화, 넉넉한 살림을 뜻합니다. 양떼를 몰면 재물이 불어나고 사람들이 따르는 길몽입니다.',
      korea: '양떼가 들판에서 평화롭게 풀을 뜯으면 집안이 평안하고 재산이 늘어난다고 봅니다. 양을 품에 안으면 순하고 착한 자녀를 얻는 태몽으로 보기도 합니다. 염소가 들이받으면 고집 센 사람과의 다툼을 조심하라는 뜻입니다.',
      vietnam: '베트남 12띠의 미(未)는 양이 아니라 염소(dê)입니다. 염소 꿈은 끈기와 생활력, 넉넉한 살림을 뜻한다고 봅니다.',
      cases: [
        ['양떼가 평화롭게 노는 꿈', '집안이 평안하고 재산이 늘어납니다.'],
        ['양떼를 모는 꿈', '사람들이 따르고 일이 커집니다.'],
        ['양을 품에 안는 꿈', '순한 자녀를 얻는 태몽으로 봅니다.'],
        ['염소에게 받히는 꿈', '고집 센 사람과의 다툼을 조심하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy dê, cừu', keywords: ['dê', 'cừu', 'đàn cừu', 'nằm mơ thấy dê'],
      summary: 'Cừu, dê tượng trưng cho sự hiền hòa, bình yên và cuộc sống no đủ. Lùa đàn cừu là tiền của tăng, nhiều người theo.',
      korea: 'Người Hàn cho rằng đàn cừu gặm cỏ yên bình là gia đạo an ổn, tài sản tăng; ôm cừu là giấc mơ báo sinh con hiền lành; bị dê húc là nên tránh tranh cãi với người cứng đầu.',
      vietnam: 'Trong 12 con giáp Việt Nam, chi Mùi là con dê (không phải cừu như Hàn Quốc). Mơ thấy dê thường nói về sự bền bỉ, chịu khó và đời sống sung túc.',
      cases: [
        ['Mơ đàn cừu yên bình', 'Gia đạo an ổn, của cải tăng.'],
        ['Mơ lùa đàn cừu', 'Nhiều người theo, việc mở rộng.'],
        ['Mơ ôm cừu', 'Giấc mơ báo có con hiền lành.'],
        ['Mơ bị dê húc', 'Tránh cãi vã với người cứng đầu.'],
      ],
    },
  },
  {
    slug: 'duck', category: 'animal', tone: 'good', emoji: '🦆',
    ko: {
      name: '오리·원앙 꿈', keywords: ['오리', '원앙', '거위', '오리 꿈'],
      summary: '물 위에 떠 있는 오리는 여유와 재물, 원앙 한 쌍은 부부 금슬과 좋은 인연을 뜻합니다.',
      korea: '원앙은 평생 짝을 지킨다고 여겨 혼례 때 나무 원앙을 주고받습니다. 그래서 원앙 한 쌍이 나오는 꿈은 좋은 인연이나 부부 화목을 뜻합니다. 오리떼가 집 마당에 모이면 재물과 사람이 모인다고 봅니다.',
      vietnam: '오리 기르는 집이 많은 베트남에서 오리(vịt) 꿈은 소박한 풍족함을 뜻하며, 오리알을 얻으면 작은 재물이 들어온다고 봅니다.',
      cases: [
        ['원앙 한 쌍을 보는 꿈', '좋은 인연이나 부부 화목을 뜻합니다.'],
        ['오리떼가 마당에 모이는 꿈', '재물과 사람이 모입니다.'],
        ['오리알을 줍는 꿈', '작은 재물이 들어옵니다.'],
        ['오리가 날아가는 꿈', '들어올 운을 놓치지 않게 서두르세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy vịt, uyên ương', keywords: ['vịt', 'uyên ương', 'ngỗng', 'trứng vịt'],
      summary: 'Vịt bơi thong thả là sự dư dả, tiền bạc; đôi uyên ương là vợ chồng hòa hợp, duyên lành.',
      korea: 'Người Hàn tin uyên ương sống chung thủy trọn đời nên tặng tượng uyên ương gỗ trong lễ cưới; mơ thấy đôi uyên ương là có duyên hoặc vợ chồng hòa thuận. Đàn vịt tụ về sân là người và của tụ về.',
      vietnam: 'Nhiều nhà ở Việt Nam nuôi vịt, nên mơ thấy vịt là sự no đủ giản dị; nhặt trứng vịt là có khoản thu nhỏ.',
      cases: [
        ['Mơ thấy đôi uyên ương', 'Duyên lành, vợ chồng hòa hợp.'],
        ['Mơ đàn vịt về sân', 'Người và của tụ về.'],
        ['Mơ nhặt trứng vịt', 'Có khoản thu nhỏ.'],
        ['Mơ vịt bay đi', 'Nhanh tay kẻo lỡ vận may.'],
      ],
    },
  },
  {
    slug: 'whale', category: 'animal', tone: 'good', emoji: '🐋',
    ko: {
      name: '고래 꿈', keywords: ['고래', '고래 꿈', '태몽'],
      summary: '고래는 큰 꿈과 큰 재물, 넓은 무대를 뜻합니다. 고래가 품에 들거나 바다에서 솟구치면 크게 될 인물을 얻는 태몽으로 봅니다.',
      korea: '거대한 고래는 "큰 그릇"의 상징이라, 고래를 보는 꿈은 사업이 크게 일어나거나 큰 기회를 만난다는 뜻입니다. 고래가 품에 안기면 큰 인물이 될 자녀의 태몽으로 풉니다.',
      vietnam: '베트남 어촌에서는 고래(cá voi)를 바다의 수호신 "꺼옹(cá Ông)"으로 모십니다. 그래서 고래 꿈은 위험에서 보호받고 큰 복을 받는 길몽으로 여깁니다.',
      cases: [
        ['고래가 바다에서 솟구치는 꿈', '큰 기회나 사업 확장을 뜻합니다.'],
        ['고래가 품에 안기는 꿈', '크게 될 자녀의 태몽입니다.'],
        ['고래를 타고 바다를 건너는 꿈', '큰 무대로 나아가 성공합니다.'],
        ['고래가 해변에 갇힌 꿈', '능력을 펼칠 곳을 찾아야 할 때입니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy cá voi', keywords: ['cá voi', 'cá Ông', 'nằm mơ thấy cá voi'],
      summary: 'Cá voi tượng trưng cho hoài bão lớn, tài lộc lớn và sân chơi rộng. Cá voi vào lòng là giấc mơ báo sinh người tài theo quan niệm Hàn Quốc.',
      korea: 'Người Hàn coi cá voi là biểu tượng “tầm vóc lớn”: mơ thấy cá voi là làm ăn bứt phá, gặp cơ hội lớn; ôm cá voi là giấc mơ báo có con sẽ làm nên chuyện lớn.',
      vietnam: 'Ngư dân Việt thờ cá voi là “cá Ông”, vị thần biển cứu người gặp nạn. Vì vậy mơ thấy cá voi được xem là điềm được che chở, gặp đại phúc.',
      cases: [
        ['Mơ cá voi vọt lên mặt biển', 'Cơ hội lớn, làm ăn mở rộng.'],
        ['Mơ ôm cá voi', 'Giấc mơ báo có con tài giỏi.'],
        ['Mơ cưỡi cá voi vượt biển', 'Bước ra sân chơi lớn và thành công.'],
        ['Mơ cá voi mắc cạn', 'Cần tìm nơi phát huy năng lực.'],
      ],
    },
  },
  {
    slug: 'shark', category: 'animal', tone: 'bad', emoji: '🦈',
    ko: {
      name: '상어 꿈', keywords: ['상어', '상어 꿈', '상어에게 물리는 꿈'],
      summary: '상어는 공격적인 경쟁자나 금전적 위험을 뜻합니다. 상어를 피하거나 잡으면 위기를 이겨 냅니다.',
      korea: '전통 해몽에는 드물지만, 요즘은 바다 속 상어처럼 내 몫을 노리는 사람이나 무리한 투자를 조심하라는 꿈으로 봅니다. 상어를 잡으면 경쟁에서 이겨 큰 이익을 얻는다고 풉니다.',
      vietnam: '베트남에서도 상어(cá mập) 꿈은 탐욕스러운 사람이나 빚, 사기를 조심하라는 경고로 봅니다.',
      cases: [
        ['상어가 주위를 맴도는 꿈', '내 몫을 노리는 사람을 조심하세요.'],
        ['상어에게 물리는 꿈', '무리한 투자나 보증을 피하세요.'],
        ['상어를 잡는 꿈', '경쟁에서 이겨 이익을 얻습니다.'],
        ['상어를 피해 배에 오르는 꿈', '위기를 무사히 넘깁니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy cá mập', keywords: ['cá mập', 'cá mập cắn'],
      summary: 'Cá mập là đối thủ hung hăng hoặc rủi ro tiền bạc. Tránh được hay bắt được cá mập là vượt qua nguy cơ.',
      korea: 'Giải mộng truyền thống Hàn ít nói đến cá mập, nhưng ngày nay người ta hiểu đó là kẻ nhòm ngó phần của mình hoặc đầu tư quá tay; bắt được cá mập là thắng cạnh tranh, được lợi lớn.',
      vietnam: 'Người Việt cũng giải mơ cá mập là lời cảnh báo về kẻ tham lam, nợ nần hay lừa đảo.',
      cases: [
        ['Mơ cá mập lượn quanh', 'Cẩn thận người nhòm ngó quyền lợi của bạn.'],
        ['Mơ bị cá mập cắn', 'Tránh đầu tư liều hay đứng ra bảo lãnh.'],
        ['Mơ bắt được cá mập', 'Thắng cạnh tranh, có lợi.'],
        ['Mơ thoát cá mập lên thuyền', 'Qua khỏi nguy hiểm.'],
      ],
    },
  },
  {
    slug: 'eagle', category: 'animal', tone: 'good', emoji: '🦅',
    ko: {
      name: '독수리 꿈', keywords: ['독수리', '매', '독수리 꿈'],
      summary: '독수리와 매는 높은 뜻과 권위, 큰 성취를 뜻합니다. 하늘 높이 나는 독수리는 출세의 길몽입니다.',
      korea: '독수리가 높이 날거나 내 팔에 앉으면 권위 있는 자리에 오르거나 큰 목표를 이룬다고 봅니다. 매사냥 전통에서 매를 길들이는 꿈은 능력 있는 사람을 부리게 된다는 뜻입니다. 독수리에게 공격당하면 윗사람의 압박을 뜻합니다.',
      vietnam: '베트남에서도 독수리(đại bàng)는 힘과 야망의 상징으로, 높이 나는 독수리 꿈은 성공과 명예를 뜻합니다.',
      cases: [
        ['독수리가 하늘 높이 나는 꿈', '출세하고 큰 목표를 이룹니다.'],
        ['독수리가 팔에 앉는 꿈', '권위 있는 자리나 인정을 얻습니다.'],
        ['매를 길들이는 꿈', '유능한 사람을 얻어 일을 키웁니다.'],
        ['독수리에게 공격당하는 꿈', '윗사람의 압박이 있습니다. 차분히 대응하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đại bàng', keywords: ['đại bàng', 'chim ưng', 'diều hâu'],
      summary: 'Đại bàng, chim ưng tượng trưng cho chí lớn, uy quyền và thành tựu lớn. Đại bàng bay cao là điềm công danh.',
      korea: 'Người Hàn cho rằng đại bàng bay cao hay đậu trên tay là lên vị trí có uy, đạt mục tiêu lớn; thuần phục chim ưng là có người tài làm việc cho mình; bị đại bàng tấn công là áp lực từ cấp trên.',
      vietnam: 'Người Việt cũng xem đại bàng là sức mạnh, hoài bão; đại bàng bay cao là thành công, danh vọng.',
      cases: [
        ['Mơ đại bàng bay cao', 'Công danh rộng mở, đạt mục tiêu lớn.'],
        ['Mơ đại bàng đậu trên tay', 'Được công nhận, có vị trí uy tín.'],
        ['Mơ thuần phục chim ưng', 'Có người tài giúp mở rộng việc.'],
        ['Mơ bị đại bàng tấn công', 'Áp lực từ cấp trên — bình tĩnh ứng phó.'],
      ],
    },
  },
  {
    slug: 'owl', category: 'animal', tone: 'mixed', emoji: '🦉',
    ko: {
      name: '부엉이 꿈', keywords: ['부엉이', '올빼미', '부엉이 꿈'],
      summary: '한국에서 부엉이는 재물을 차곡차곡 모으는 동물로 길하게 보지만, 베트남에서는 흉한 소식의 새로 여겨 해석이 크게 다릅니다.',
      korea: '"부엉이 살림"(모르는 사이에 살림이 늘어나는 집)이라는 말처럼 부엉이는 재물을 모으는 상징입니다. 부엉이가 집에 날아들면 재물이 쌓이고, 부엉이 눈과 마주치면 지혜와 통찰을 얻는다고 봅니다.',
      vietnam: '베트남에서는 올빼미(cú) 울음을 불길한 소식으로 여기는 전통이 있어, 올빼미 꿈은 건강이나 집안일을 살피라는 경고로 풉니다.',
      cases: [
        ['부엉이가 집에 날아드는 꿈', '한국에서는 재물이 차곡차곡 쌓이는 꿈입니다.'],
        ['부엉이와 눈이 마주치는 꿈', '지혜와 통찰을 얻습니다.'],
        ['올빼미가 밤에 우는 꿈', '베트남에서는 집안의 건강을 살피라는 뜻으로 봅니다.'],
        ['부엉이가 날아가는 꿈', '모은 재물을 지키고 지출을 점검하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy cú', keywords: ['cú', 'cú mèo', 'chim cú', 'cú kêu'],
      summary: 'Người Hàn xem cú là con vật tích của, điềm lành; còn người Việt xưa coi tiếng cú là điềm gở — hai cách giải rất khác nhau.',
      korea: 'Người Hàn có thành ngữ “gia sản nhà cú” để nói nhà nào cứ âm thầm giàu lên, nên cú là biểu tượng tích lũy tài sản. Cú bay vào nhà là của cải dồn dần; nhìn vào mắt cú là được trí tuệ, sáng suốt.',
      vietnam: 'Người Việt có câu “cú kêu ra ma”, xưa coi tiếng cú là báo điềm không lành; vì vậy mơ thấy cú thường được giải là nên chăm lo sức khỏe, việc nhà.',
      cases: [
        ['Mơ cú bay vào nhà', 'Theo người Hàn: của cải tích lũy dần.'],
        ['Mơ nhìn vào mắt cú', 'Được trí tuệ, sáng suốt.'],
        ['Mơ cú kêu ban đêm', 'Theo người Việt: quan tâm sức khỏe gia đình.'],
        ['Mơ cú bay đi', 'Giữ gìn của cải, xem lại chi tiêu.'],
      ],
    },
  },
  {
    slug: 'crow', category: 'animal', tone: 'mixed', emoji: '🪶',
    ko: {
      name: '까마귀 꿈', keywords: ['까마귀', '까마귀 꿈', '까마귀 우는 꿈'],
      summary: '까마귀는 흔히 흉조로 여겨 나쁜 소식을 조심하라는 뜻이지만, 효도와 지혜의 새로 보는 시각도 있습니다.',
      korea: '까마귀가 울면 궂은 소식이 온다는 속설이 있어, 까마귀 떼가 울거나 집에 앉으면 건강과 구설을 조심하라고 풉니다. 한편 늙은 어미를 먹여 살린다는 "반포지효"의 새이기도 해, 까마귀가 먹이를 물어 오면 효도나 보답을 받는다고 봅니다.',
      vietnam: '베트남에서도 까마귀(quạ) 꿈은 대체로 나쁜 소식이나 시비를 조심하라는 경고로 봅니다.',
      cases: [
        ['까마귀 떼가 우는 꿈', '구설과 궂은 소식을 조심하세요.'],
        ['까마귀가 집에 앉는 꿈', '집안 어른의 건강을 살피세요.'],
        ['까마귀가 먹이를 물어 오는 꿈', '자녀의 효도나 뜻밖의 보답을 받습니다.'],
        ['까마귀를 쫓아내는 꿈', '나쁜 기운을 물리치고 걱정이 사라집니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy quạ', keywords: ['quạ', 'con quạ', 'quạ kêu'],
      summary: 'Quạ thường bị xem là điềm xấu, nhắc cẩn thận tin không vui; nhưng người Hàn cũng coi quạ là loài chim hiếu thảo, thông minh.',
      korea: 'Người Hàn tin quạ kêu là có tin buồn, nên đàn quạ kêu hay đậu trên nhà là nên cẩn thận sức khỏe, thị phi. Nhưng quạ cũng là loài “mớm mồi nuôi mẹ già” (phản bộ chi hiếu), nên quạ tha mồi về là được con cái hiếu thảo, được đền đáp.',
      vietnam: 'Người Việt cũng thường giải mơ thấy quạ là tin không vui hoặc chuyện thị phi.',
      cases: [
        ['Mơ đàn quạ kêu', 'Cẩn thận thị phi, tin buồn.'],
        ['Mơ quạ đậu trên nhà', 'Quan tâm sức khỏe người lớn trong nhà.'],
        ['Mơ quạ tha mồi về', 'Được con cái hiếu thảo hoặc được đền đáp.'],
        ['Mơ đuổi quạ đi', 'Xua được điều xấu, hết lo.'],
      ],
    },
  },
  {
    slug: 'peacock', category: 'animal', tone: 'good', emoji: '🦚',
    ko: {
      name: '공작 꿈', keywords: ['공작', '공작새', '공작 꿈'],
      summary: '꼬리를 활짝 편 공작은 명예와 인기, 화려한 성공을 뜻하는 길몽입니다.',
      korea: '공작이 꼬리를 펼치면 내 능력이 드러나 주목받고 명예를 얻는다고 봅니다. 공작이 집에 들어오면 경사가, 공작 깃털을 얻으면 상이나 인정을 받는다고 풉니다. 다만 공작처럼 겉치레에 치우치지 말라는 뜻으로 보기도 합니다.',
      vietnam: '베트남에서도 공작(công)은 아름다움과 고귀함의 상징으로, 공작 꿈은 명예와 좋은 인연을 뜻합니다.',
      cases: [
        ['공작이 꼬리를 펼치는 꿈', '능력을 인정받고 주목받습니다.'],
        ['공작이 집에 들어오는 꿈', '집안에 경사가 생깁니다.'],
        ['공작 깃털을 얻는 꿈', '상이나 인정을 받습니다.'],
        ['공작이 깃털을 잃는 꿈', '겉치레보다 실속을 챙기세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy chim công', keywords: ['chim công', 'công xòe đuôi', 'lông công'],
      summary: 'Chim công xòe đuôi là điềm lành về danh dự, được yêu mến và thành công rực rỡ.',
      korea: 'Người Hàn cho rằng công xòe đuôi là năng lực được thể hiện, được chú ý và có danh dự; công vào nhà là có hỷ sự; được lông công là được khen thưởng. Đôi khi cũng là lời nhắc đừng chạy theo hình thức.',
      vietnam: 'Người Việt cũng xem chim công là biểu tượng của vẻ đẹp, sự cao quý; mơ thấy công là danh dự và duyên lành.',
      cases: [
        ['Mơ công xòe đuôi', 'Năng lực được công nhận, được chú ý.'],
        ['Mơ công vào nhà', 'Nhà có hỷ sự.'],
        ['Mơ nhặt được lông công', 'Được khen thưởng, ghi nhận.'],
        ['Mơ công rụng lông', 'Chú trọng thực chất hơn hình thức.'],
      ],
    },
  },
  {
    slug: 'deer', category: 'animal', tone: 'good', emoji: '🦌',
    ko: {
      name: '사슴 꿈', keywords: ['사슴', '녹용', '사슴 꿈', '태몽'],
      summary: '사슴은 장수와 벼슬, 맑은 인연을 뜻하는 길몽입니다. 사슴 녹(鹿)이 녹봉 녹(祿)과 소리가 같아 승진과 재물의 상징이기도 합니다.',
      korea: '사슴은 십장생 가운데 하나로 건강과 장수를 뜻하고, 사슴이 집에 들어오면 승진이나 녹봉(월급)이 오른다고 봅니다. 순한 사슴을 품으면 맑고 귀한 자녀를 얻는 태몽으로 풉니다.',
      vietnam: '베트남어에서도 사슴(hươu, nai)을 뜻하는 한자 "鹿"이 복록의 "祿(lộc)"과 소리가 같아, 사슴 꿈은 "lộc"이 들어오는 길몽으로 봅니다.',
      cases: [
        ['사슴이 집에 들어오는 꿈', '승진이나 수입 증가를 뜻합니다.'],
        ['사슴을 품에 안는 꿈', '맑고 귀한 자녀의 태몽입니다.'],
        ['사슴 떼를 보는 꿈', '건강과 복이 이어집니다.'],
        ['사슴이 달아나는 꿈', '기회를 서둘러 잡으세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy hươu, nai', keywords: ['hươu', 'nai', 'nhung hươu'],
      summary: 'Hươu nai là điềm lành về sống thọ, quan lộc và duyên lành. Chữ “lộc” (鹿, con hươu) đồng âm với “lộc” (祿, bổng lộc).',
      korea: 'Hươu là một trong thập trường sinh của người Hàn, tượng trưng sức khỏe và tuổi thọ. Hươu vào nhà là thăng chức, tăng lương; ôm hươu hiền là giấc mơ báo có con thanh tú.',
      vietnam: 'Trong tiếng Việt, chữ Hán “鹿” (hươu) đọc là “lộc”, trùng âm với “祿” (lộc, bổng lộc), nên mơ thấy hươu nai được xem là điềm có lộc.',
      cases: [
        ['Mơ hươu vào nhà', 'Thăng chức, thu nhập tăng.'],
        ['Mơ ôm hươu', 'Giấc mơ báo có con thanh tú.'],
        ['Mơ thấy đàn hươu', 'Sức khỏe và phúc lộc nối tiếp.'],
        ['Mơ hươu chạy mất', 'Nắm lấy cơ hội kịp thời.'],
      ],
    },
  },
  {
    slug: 'wolf', category: 'animal', tone: 'bad', emoji: '🐺',
    ko: {
      name: '늑대 꿈', keywords: ['늑대', '이리', '늑대 꿈'],
      summary: '늑대는 숨은 적이나 속셈 있는 사람을 뜻합니다. 늑대를 물리치면 위험을 이겨 내는 꿈입니다.',
      korea: '늑대가 집 주변을 맴돌면 내 것을 노리는 사람이 있으니 조심하라는 뜻으로 봅니다. 늑대 무리에게 쫓기면 여러 사람의 압박을 받는 상황, 늑대를 길들이면 거친 상대를 내 편으로 만든다고 풉니다.',
      vietnam: '베트남에서도 늑대(sói) 꿈은 배신이나 위험한 사람을 조심하라는 경고로 봅니다.',
      cases: [
        ['늑대가 집 주변을 맴도는 꿈', '내 것을 노리는 사람을 조심하세요.'],
        ['늑대 무리에게 쫓기는 꿈', '여러 방면의 압박이 있습니다. 하나씩 정리하세요.'],
        ['늑대를 물리치는 꿈', '위험을 이겨 냅니다.'],
        ['늑대를 길들이는 꿈', '거친 상대를 내 편으로 만듭니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy sói', keywords: ['sói', 'chó sói', 'bầy sói'],
      summary: 'Sói là kẻ thù giấu mặt hoặc người có ý đồ. Đánh lui được sói là vượt qua nguy hiểm.',
      korea: 'Người Hàn cho rằng sói lảng vảng quanh nhà là có người nhòm ngó của mình; bị bầy sói đuổi là chịu áp lực từ nhiều phía; thuần phục sói là biến đối thủ khó chịu thành người phe mình.',
      vietnam: 'Người Việt cũng giải mơ thấy sói là cảnh báo phản bội, người nguy hiểm.',
      cases: [
        ['Mơ sói lảng vảng quanh nhà', 'Cẩn thận người nhòm ngó tài sản.'],
        ['Mơ bị bầy sói đuổi', 'Áp lực nhiều phía — xử lý từng việc.'],
        ['Mơ đánh lui sói', 'Vượt qua nguy hiểm.'],
        ['Mơ thuần phục sói', 'Biến đối thủ thành đồng minh.'],
      ],
    },
  },
  {
    slug: 'lion', category: 'animal', tone: 'good', emoji: '🦁',
    ko: {
      name: '사자 꿈', keywords: ['사자', '사자 꿈', '태몽'],
      summary: '사자는 권위와 용기, 리더십을 뜻합니다. 사자를 다스리거나 사자가 따르면 높은 자리에 오르는 길몽입니다.',
      korea: '사자가 집에 들어오거나 나를 따르면 권위 있는 자리나 큰 후원을 얻는다고 봅니다. 아들을 얻는 태몽으로도 꼽힙니다. 사자탈춤처럼 잡귀를 쫓는 상징이라 사자를 보면 나쁜 기운이 물러간다고 풉니다. 사자에게 쫓기면 강한 상대의 압박입니다.',
      vietnam: '베트남에서 사자(sư tử)는 사자춤(múa lân sư rồng)에서 볼 수 있듯 액운을 쫓고 복을 부르는 상징으로, 사자 꿈은 용기와 성공을 뜻합니다.',
      cases: [
        ['사자가 나를 따르는 꿈', '권위 있는 자리나 큰 후원을 얻습니다.'],
        ['사자를 품에 안는 꿈', '태몽으로 봅니다.'],
        ['사자가 포효하는 꿈', '나쁜 기운이 물러가고 명성이 퍼집니다.'],
        ['사자에게 쫓기는 꿈', '강한 상대의 압박이 있습니다. 정면 대결은 피하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy sư tử', keywords: ['sư tử', 'múa lân', 'nằm mơ thấy sư tử'],
      summary: 'Sư tử là uy quyền, lòng dũng cảm và khả năng lãnh đạo. Điều khiển được sư tử là điềm lên vị trí cao.',
      korea: 'Người Hàn cho rằng sư tử vào nhà hay đi theo mình là có vị trí uy quyền, có người nâng đỡ; đây cũng là giấc mơ báo sinh con trai. Múa mặt nạ sư tử ở Hàn Quốc dùng để trừ tà, nên thấy sư tử là điều xấu lùi xa.',
      vietnam: 'Với người Việt, sư tử gắn với múa lân sư rồng — xua đuổi xui xẻo, đón may mắn; mơ thấy sư tử là dũng khí và thành công.',
      cases: [
        ['Mơ sư tử đi theo mình', 'Có vị trí uy quyền, được nâng đỡ.'],
        ['Mơ ôm sư tử con', 'Giấc mơ báo có con.'],
        ['Mơ sư tử gầm', 'Điều xấu lùi xa, danh tiếng lan rộng.'],
        ['Mơ bị sư tử đuổi', 'Áp lực từ đối thủ mạnh — tránh đối đầu trực diện.'],
      ],
    },
  },
  {
    slug: 'fox', category: 'animal', tone: 'bad', emoji: '🦊',
    ko: {
      name: '여우 꿈', keywords: ['여우', '구미호', '여우 꿈'],
      summary: '여우는 꾀와 유혹, 속임수를 뜻합니다. 여우에게 홀리면 달콤한 말에 속지 않도록 조심하라는 꿈입니다.',
      korea: '구미호 이야기처럼 여우는 사람을 홀리는 동물이라, 여우가 다가오면 유혹이나 사기를 조심하라는 뜻입니다. 반대로 여우를 잡거나 쫓아내면 나를 속이려던 사람을 알아채고 피한다고 풉니다.',
      vietnam: '베트남에서도 여우(cáo)는 교활함의 상징이라, 여우 꿈은 주변의 거짓말이나 이간질을 조심하라는 뜻으로 봅니다.',
      cases: [
        ['여우가 다가오는 꿈', '달콤한 말과 유혹을 조심하세요.'],
        ['여우에게 홀리는 꿈', '계약이나 투자 제안을 꼼꼼히 확인하세요.'],
        ['여우를 잡는 꿈', '속이려던 사람을 알아채고 피합니다.'],
        ['꼬리 여러 개 달린 여우를 보는 꿈', '복잡한 관계에서 거리를 두세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy cáo', keywords: ['cáo', 'con cáo', 'hồ ly', 'cáo chín đuôi'],
      summary: 'Cáo là mưu mẹo, sự cám dỗ và lừa lọc. Bị cáo mê hoặc là lời nhắc đừng tin lời đường mật.',
      korea: 'Như truyện hồ ly chín đuôi (구미호), cáo trong văn hóa Hàn là loài mê hoặc người; cáo đến gần là nên đề phòng cám dỗ, lừa gạt. Bắt hay đuổi được cáo là nhận ra kẻ định lừa mình.',
      vietnam: 'Người Việt cũng xem cáo là biểu tượng xảo quyệt; mơ thấy cáo là coi chừng dối trá, ly gián.',
      cases: [
        ['Mơ cáo đến gần', 'Cẩn thận lời ngọt và cám dỗ.'],
        ['Mơ bị cáo mê hoặc', 'Xem kỹ hợp đồng, lời mời đầu tư.'],
        ['Mơ bắt được cáo', 'Nhận ra và tránh được kẻ lừa gạt.'],
        ['Mơ thấy cáo nhiều đuôi', 'Giữ khoảng cách với quan hệ phức tạp.'],
      ],
    },
  },
  {
    slug: 'crab', category: 'animal', tone: 'mixed', emoji: '🦀',
    ko: {
      name: '게 꿈', keywords: ['게', '꽃게', '대게', '게 꿈'],
      summary: '게는 단단한 껍데기처럼 지키는 재물, 또 옆걸음처럼 돌아가는 일을 뜻합니다. 큰 게를 잡으면 재물이 들어옵니다.',
      korea: '크고 살이 꽉 찬 게를 잡거나 받으면 재물이 들어온다고 봅니다. 게가 옆으로 기어가면 일이 곧장 가지 않고 돌아가니 서두르지 말라는 뜻이며, 게에게 물리면 작은 손해를 조심하라고 풉니다.',
      vietnam: '베트남에서 게(cua)는 즐겨 먹는 귀한 해산물이라, 게를 잡는 꿈은 먹을 복과 재물이 생긴다고 봅니다.',
      cases: [
        ['큰 게를 잡는 꿈', '재물이 들어옵니다.'],
        ['게가 옆으로 기어가는 꿈', '일이 돌아가니 서두르지 마세요.'],
        ['게에게 물리는 꿈', '작은 손해를 조심하세요.'],
        ['게를 맛있게 먹는 꿈', '먹을 복과 즐거운 모임이 생깁니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy cua', keywords: ['cua', 'cua biển', 'bắt cua', 'cua kẹp'],
      summary: 'Cua là của cải được giữ chắc như lớp mai cứng, và cũng là việc đi đường vòng như bước ngang. Bắt được cua to là tiền vào.',
      korea: 'Người Hàn cho rằng bắt hay được cho cua to chắc thịt là có tiền; cua bò ngang là việc không đi thẳng, đừng vội; bị cua kẹp là đề phòng thiệt hại nhỏ.',
      vietnam: 'Cua là món hải sản quý người Việt ưa chuộng, nên mơ bắt cua là có lộc ăn uống, có tiền.',
      cases: [
        ['Mơ bắt được cua to', 'Có tiền vào.'],
        ['Mơ cua bò ngang', 'Việc đi đường vòng — đừng nóng vội.'],
        ['Mơ bị cua kẹp', 'Cẩn thận thiệt hại nhỏ.'],
        ['Mơ ăn cua ngon', 'Có lộc ăn uống, gặp gỡ vui vẻ.'],
      ],
    },
  },
  {
    slug: 'octopus', category: 'animal', tone: 'mixed', emoji: '🐙',
    ko: {
      name: '문어 꿈', keywords: ['문어', '낙지', '오징어', '문어 꿈', '태몽'],
      summary: '문어(文魚)는 이름에 글월 문(文)이 들어가 학식과 지혜의 상징입니다. 큰 문어는 공부 잘하는 자녀의 태몽으로 봅니다.',
      korea: '문어는 먹물을 품은 "글 아는 물고기"라 하여 제사상과 잔칫상에 오르고, 큰 문어를 잡는 꿈은 학업 성취나 합격, 똑똑한 자녀의 태몽으로 풉니다. 문어 다리에 휘감기면 여러 일과 관계에 얽매여 있다는 뜻입니다.',
      vietnam: '베트남에서 문어(bạch tuộc) 꿈은 여러 방면으로 손을 뻗는 수완을 뜻하지만, 휘감기면 복잡한 관계를 조심하라고 봅니다.',
      cases: [
        ['큰 문어를 잡는 꿈', '학업 성취나 합격을 뜻합니다.'],
        ['문어를 품에 안는 꿈', '똑똑한 자녀의 태몽으로 봅니다.'],
        ['문어 다리에 휘감기는 꿈', '여러 일에 얽매여 있습니다. 우선순위를 정하세요.'],
        ['문어가 먹물을 뿜는 꿈', '상황이 흐려지니 결정을 잠시 미루세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy bạch tuộc', keywords: ['bạch tuộc', 'mực', 'nằm mơ thấy bạch tuộc'],
      summary: 'Người Hàn gọi bạch tuộc là “văn ngư” (文魚 — cá có chữ), biểu tượng học thức; bạch tuộc lớn là giấc mơ báo sinh con học giỏi.',
      korea: 'Vì có mực trong bụng, bạch tuộc được người Hàn gọi là “cá biết chữ”, thường bày trên mâm cúng, mâm tiệc. Bắt được bạch tuộc to là thi đỗ, học hành tiến bộ, hoặc giấc mơ báo có con thông minh. Bị xúc tu quấn là vướng nhiều việc, nhiều mối quan hệ.',
      vietnam: 'Người Việt xem bạch tuộc là sự khéo xoay xở nhiều mặt, nhưng bị quấn chặt là nên cẩn thận quan hệ rắc rối.',
      cases: [
        ['Mơ bắt bạch tuộc to', 'Học hành tiến bộ, thi đỗ.'],
        ['Mơ ôm bạch tuộc', 'Giấc mơ báo có con thông minh.'],
        ['Mơ bị xúc tu quấn', 'Vướng nhiều việc — sắp xếp ưu tiên.'],
        ['Mơ bạch tuộc phun mực', 'Tình hình mờ mịt — tạm hoãn quyết định.'],
      ],
    },
  },
  {
    slug: 'phoenix', category: 'animal', tone: 'good', emoji: '🔥',
    ko: {
      name: '봉황 꿈', keywords: ['봉황', '불사조', '봉황 꿈', '태몽'],
      summary: '봉황은 가장 귀한 상서로운 새로, 큰 명예와 성공, 귀한 자녀를 뜻하는 최고의 길몽입니다.',
      korea: '봉황은 태평성대에만 나타난다는 새라 대통령 문장에도 쓰입니다. 봉황이 날아오르거나 품에 들면 큰 명예와 높은 지위, 귀하게 될 딸을 얻는 태몽으로 봅니다.',
      vietnam: '베트남에서 봉황(phượng hoàng)은 용·기린·거북과 함께 사령(tứ linh)으로, 고귀함과 행복한 결혼을 상징합니다. 봉황 꿈은 큰 경사와 성공을 뜻합니다.',
      cases: [
        ['봉황이 날아오르는 꿈', '큰 명예와 높은 지위를 얻습니다.'],
        ['봉황이 품에 드는 꿈', '귀한 자녀의 태몽입니다.'],
        ['봉황 한 쌍을 보는 꿈', '좋은 결혼이나 부부 화합을 뜻합니다.'],
        ['봉황이 불에서 다시 태어나는 꿈', '어려움 끝에 화려하게 재기합니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy phượng hoàng', keywords: ['phượng hoàng', 'chim phượng', 'phượng'],
      summary: 'Phượng hoàng là loài chim linh thiêng bậc nhất — điềm đại cát về danh vọng, thành công và con quý.',
      korea: 'Người Hàn tin phượng hoàng chỉ xuất hiện thời thái bình, nên hình phượng còn được dùng làm biểu tượng của Tổng thống. Phượng bay lên hay vào lòng là danh vọng lớn, địa vị cao, hoặc giấc mơ báo sinh con gái quý.',
      vietnam: 'Với người Việt, phượng là một trong tứ linh (long, lân, quy, phụng), tượng trưng sự cao quý và hôn nhân hạnh phúc.',
      cases: [
        ['Mơ phượng hoàng bay lên', 'Danh vọng lớn, địa vị cao.'],
        ['Mơ phượng hoàng vào lòng', 'Giấc mơ báo có con quý.'],
        ['Mơ thấy đôi phượng', 'Hôn nhân tốt đẹp, vợ chồng hòa hợp.'],
        ['Mơ phượng hoàng tái sinh từ lửa', 'Vượt khó và trở lại rực rỡ.'],
      ],
    },
  },
  {
    slug: 'bat', category: 'animal', tone: 'mixed', emoji: '🦇',
    ko: {
      name: '박쥐 꿈', keywords: ['박쥐', '박쥐 꿈'],
      summary: '박쥐는 요즘엔 으스스하게 여기지만, 전통적으로는 복(福)을 부르는 무늬였습니다. 집에 날아들면 복이 든다고 봅니다.',
      korea: '박쥐 복(蝠)이 복 복(福)과 소리가 같아, 옛 가구와 베갯모에 박쥐 무늬를 새겨 복을 빌었습니다. 그래서 박쥐가 집에 들어오는 꿈은 복과 재물이 드는 꿈입니다. 다만 박쥐 떼에 둘러싸이면 이쪽저쪽 오가는 사람을 조심하라는 뜻입니다.',
      vietnam: '베트남에서도 박쥐(dơi)의 한자 蝠가 福(phúc)과 소리가 같아 전통 문양에 쓰였고, 박쥐 꿈을 복과 장수로 풉니다.',
      cases: [
        ['박쥐가 집에 날아드는 꿈', '복과 재물이 들어옵니다.'],
        ['박쥐 다섯 마리를 보는 꿈', '오복(五福)이 깃든다는 길몽입니다.'],
        ['박쥐 떼에 둘러싸이는 꿈', '이쪽저쪽 말을 옮기는 사람을 조심하세요.'],
        ['박쥐에게 물리는 꿈', '건강과 위생을 챙기세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy dơi', keywords: ['dơi', 'con dơi', 'đàn dơi'],
      summary: 'Ngày nay dơi gợi cảm giác rờn rợn, nhưng xưa kia hình dơi là biểu tượng của phúc. Dơi bay vào nhà là phúc đến.',
      korea: 'Chữ “蝠” (dơi) đồng âm với “福” (phúc), nên người Hàn xưa chạm hình dơi lên tủ, gối để cầu phúc; dơi bay vào nhà là phúc lộc vào. Bị đàn dơi vây quanh là nên đề phòng kẻ hai mặt.',
      vietnam: 'Người Việt cũng dùng hình dơi trong hoa văn truyền thống vì “dơi” (蝠) đồng âm “phúc” (福); mơ thấy dơi là phúc và thọ.',
      cases: [
        ['Mơ dơi bay vào nhà', 'Phúc lộc vào nhà.'],
        ['Mơ thấy năm con dơi', 'Điềm “ngũ phúc lâm môn”.'],
        ['Mơ bị đàn dơi vây', 'Đề phòng kẻ hai mặt, ngồi lê đôi mách.'],
        ['Mơ bị dơi cắn', 'Giữ gìn sức khỏe, vệ sinh.'],
      ],
    },
  },
  {
    slug: 'mosquito', category: 'animal', tone: 'bad', emoji: '🦟',
    ko: {
      name: '모기·파리 꿈', keywords: ['모기', '파리', '모기 꿈', '파리 꿈'],
      summary: '모기와 파리는 자잘한 골칫거리와 내 기운을 빼앗는 사람을 뜻합니다. 깨끗이 쫓아내면 근심이 사라집니다.',
      korea: '모기에게 물리거나 파리가 꼬이면 귀찮은 부탁이나 작은 지출이 이어진다는 뜻으로 봅니다. 모기를 잡거나 파리를 쫓아내면 골칫거리가 정리되고, 방충망을 치는 꿈은 미리 대비해 손해를 막는다고 풉니다.',
      vietnam: '모기가 많은 베트남에서는 모기(muỗi) 꿈을 잔병이나 소인배의 방해를 조심하라는 뜻으로 봅니다.',
      cases: [
        ['모기에게 물리는 꿈', '귀찮은 부탁이나 작은 지출이 생깁니다.'],
        ['파리가 꼬이는 꿈', '내 기운을 빼앗는 관계를 정리하세요.'],
        ['모기를 잡는 꿈', '골칫거리가 정리됩니다.'],
        ['방충망을 치는 꿈', '미리 대비해 손해를 막습니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy muỗi, ruồi', keywords: ['muỗi', 'ruồi', 'muỗi đốt'],
      summary: 'Muỗi, ruồi là những phiền toái lặt vặt và kẻ làm hao sức bạn. Xua sạch được là hết lo.',
      korea: 'Người Hàn cho rằng bị muỗi đốt hay ruồi bu là liên tục có lời nhờ vả phiền phức, chi tiêu lặt vặt; đập muỗi, đuổi ruồi là rắc rối được dọn sạch; giăng màn là phòng trước nên tránh thiệt.',
      vietnam: 'Ở Việt Nam muỗi nhiều, nên mơ thấy muỗi thường được giải là đề phòng ốm vặt hoặc kẻ tiểu nhân quấy phá.',
      cases: [
        ['Mơ bị muỗi đốt', 'Có lời nhờ vả phiền hoặc khoản chi nhỏ.'],
        ['Mơ ruồi bu quanh', 'Dứt bớt quan hệ làm hao sức mình.'],
        ['Mơ đập được muỗi', 'Rắc rối được giải quyết.'],
        ['Mơ giăng màn chống muỗi', 'Phòng trước nên tránh được thiệt hại.'],
      ],
    },
  },
  {
    slug: 'ant', category: 'animal', tone: 'good', emoji: '🐜',
    ko: {
      name: '개미 꿈', keywords: ['개미', '개미떼', '개미 꿈'],
      summary: '개미는 부지런함과 협력, 차곡차곡 쌓이는 재물을 뜻합니다. 개미가 줄지어 먹이를 나르면 살림이 늘어나는 꿈입니다.',
      korea: '"개미처럼 모은다"는 말처럼 개미떼가 집으로 먹이를 나르면 재물이 조금씩 쌓인다고 봅니다. 개미가 이사 가듯 줄지어 집을 나가면 지출이나 이동이 생기고, 개미에게 물리면 사소한 일로 신경 쓰게 된다고 풉니다.',
      vietnam: '베트남에서도 개미(kiến)는 근면과 단결의 상징으로, 개미떼는 함께 일해 성공하거나 손님이 많아진다고 봅니다.',
      cases: [
        ['개미떼가 먹이를 나르는 꿈', '재물이 차곡차곡 쌓입니다.'],
        ['개미가 집 밖으로 줄지어 나가는 꿈', '지출이나 이동이 생깁니다.'],
        ['개미에게 물리는 꿈', '사소한 일로 신경 쓸 일이 생깁니다.'],
        ['개미집을 보는 꿈', '팀워크로 일을 이룹니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy kiến', keywords: ['kiến', 'đàn kiến', 'kiến cắn', 'tổ kiến'],
      summary: 'Kiến tượng trưng cho sự cần cù, đoàn kết và của cải tích dần. Đàn kiến tha mồi về nhà là đời sống khấm khá.',
      korea: 'Người Hàn có câu “gom góp như kiến”, nên đàn kiến tha mồi vào nhà là của cải tích dần; kiến nối đuôi ra khỏi nhà là có khoản chi hoặc chuyển dời; bị kiến cắn là phiền lòng vì chuyện nhỏ.',
      vietnam: 'Người Việt cũng xem kiến là chăm chỉ, đoàn kết; đàn kiến là làm ăn thành công nhờ hợp sức, buôn bán đông khách.',
      cases: [
        ['Mơ đàn kiến tha mồi về', 'Của cải tích dần.'],
        ['Mơ kiến bò ra khỏi nhà', 'Có khoản chi hoặc thay đổi chỗ ở.'],
        ['Mơ bị kiến cắn', 'Phiền lòng vì việc nhỏ.'],
        ['Mơ thấy tổ kiến', 'Thành công nhờ làm việc nhóm.'],
      ],
    },
  },
  {
    slug: 'swallow', category: 'animal', tone: 'good', emoji: '🌸',
    ko: {
      name: '제비 꿈', keywords: ['제비', '제비집', '제비 꿈', '흥부'],
      summary: '제비는 봄소식과 복을 물어다 주는 새입니다. 제비가 집에 둥지를 틀면 집안에 복이 드는 길몽입니다.',
      korea: '흥부전에서 다리를 고쳐 준 제비가 박씨를 물어다 주었듯, 제비는 착한 마음에 복으로 보답하는 새입니다. 제비가 처마에 집을 지으면 집안이 번창하고, 제비가 무언가를 물어 오면 뜻밖의 행운이 생긴다고 봅니다.',
      vietnam: '베트남에서는 "én bay báo xuân"(제비가 봄을 알린다)이라 하여 제비(chim én) 꿈을 새 출발과 기쁜 소식으로 봅니다.',
      cases: [
        ['제비가 처마에 집을 짓는 꿈', '집안이 번창하고 복이 듭니다.'],
        ['제비가 무언가를 물어 오는 꿈', '뜻밖의 행운이나 보답이 있습니다.'],
        ['제비 떼가 날아오는 꿈', '반가운 소식과 새 출발이 있습니다.'],
        ['제비집이 무너지는 꿈', '집안일과 가족을 살피세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy chim én', keywords: ['chim én', 'én', 'tổ én', 'chim yến'],
      summary: 'Chim én mang tin xuân và phúc lộc. Én làm tổ trong nhà là điềm nhà có phúc.',
      korea: 'Trong truyện Heungbu của Hàn Quốc, con én được chàng Heungbu chữa chân đã ngậm hạt bầu mang của cải đến đền ơn, nên én là loài chim báo đáp người hiền. Én làm tổ dưới mái nhà là gia đạo hưng thịnh; én ngậm vật gì về là có may mắn bất ngờ.',
      vietnam: 'Người Việt có câu “én bay báo xuân”, nên mơ thấy chim én là khởi đầu mới, tin vui.',
      cases: [
        ['Mơ én làm tổ trên mái', 'Gia đạo hưng thịnh, có phúc.'],
        ['Mơ én ngậm đồ về', 'May mắn hoặc được đền đáp bất ngờ.'],
        ['Mơ đàn én bay về', 'Tin vui, khởi đầu mới.'],
        ['Mơ tổ én bị vỡ', 'Quan tâm việc nhà, người thân.'],
      ],
    },
  },
];
