import type { Dream } from './types';

export const SITUATION_DREAMS_6: Dream[] = [
  {
    slug: 'airplane', category: 'situation', tone: 'good', emoji: '✈️',
    ko: {
      name: '비행기 꿈', keywords: ['비행기', '비행기 꿈', '비행기 타는 꿈', '공항', '비행기 추락'],
      summary: '비행기는 큰 도약과 해외, 새로운 출발을 뜻합니다. 비행기가 힘차게 이륙하면 일이 빠르게 높이 오르는 길몽입니다.',
      korea: '비행기를 타고 이륙하면 승진이나 사업 확장처럼 한 단계 크게 도약하고, 해외로 갈 일이 생긴다고 봅니다. 공항에서 누군가를 배웅하면 이별 뒤 새 출발이 있고, 비행기를 놓치면 기회를 미루지 말라는 뜻입니다. 비행기가 흔들리거나 추락하면 실제 사고가 아니라 계획이 너무 서두르고 있다는 경고이니 점검하세요.',
      vietnam: '베트남에서 비행기(máy bay) 꿈은 출세와 해외 취업·유학, 먼 길의 행운을 뜻합니다.',
      cases: [
        ['비행기가 힘차게 이륙하는 꿈', '한 단계 크게 도약합니다.'],
        ['공항에서 배웅하는 꿈', '이별 뒤 새 출발이 있습니다.'],
        ['비행기를 놓치는 꿈', '기회를 미루지 마세요.'],
        ['비행기가 흔들리거나 추락하는 꿈', '서두르는 계획을 점검하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy máy bay', keywords: ['máy bay', 'đi máy bay', 'sân bay', 'máy bay rơi'],
      summary: 'Máy bay là bước nhảy lớn, nước ngoài và khởi đầu mới. Máy bay cất cánh mạnh mẽ là việc lên nhanh và cao.',
      korea: 'Người Hàn cho rằng đi máy bay cất cánh là thăng chức, mở rộng làm ăn — tiến một bước lớn, có dịp ra nước ngoài; tiễn ai ở sân bay là chia tay rồi khởi đầu mới; lỡ chuyến bay là đừng trì hoãn cơ hội; máy bay rung lắc hay rơi không phải điềm tai nạn mà là nhắc kế hoạch đang quá vội.',
      vietnam: 'Người Việt giải mơ thấy máy bay là thăng tiến, đi làm, du học nước ngoài, may mắn đường xa.',
      cases: [
        ['Mơ máy bay cất cánh', 'Tiến một bước lớn.'],
        ['Mơ tiễn ai ở sân bay', 'Chia tay rồi khởi đầu mới.'],
        ['Mơ lỡ chuyến bay', 'Đừng trì hoãn cơ hội.'],
        ['Mơ máy bay rơi', 'Xem lại kế hoạch đang quá vội.'],
      ],
    },
  },
  {
    slug: 'elevator', category: 'situation', tone: 'mixed', emoji: '🛗',
    ko: {
      name: '엘리베이터 꿈', keywords: ['엘리베이터', '엘리베이터 꿈', '엘리베이터에 갇히는 꿈', '승강기'],
      summary: '엘리베이터는 빠른 오르내림, 즉 지위와 운의 급한 변화를 뜻합니다. 쭉 올라가면 빠르게 인정받는 꿈입니다.',
      korea: '엘리베이터가 쭉 올라가면 승진이나 성과로 빠르게 인정받는다고 봅니다. 갑자기 뚝 떨어지면 지나친 기대나 무리한 계획을 조심하고, 엘리베이터에 갇히면 일이 잠시 정체되니 조급해하지 말라는 뜻입니다. 문이 열리지 않으면 다른 길(계단)을 찾아보라는 꿈입니다.',
      vietnam: '베트남에서 엘리베이터(thang máy) 꿈은 지위의 변화를 뜻합니다. 올라가면 승진, 내려가면 손실을 조심하라고 봅니다.',
      cases: [
        ['엘리베이터가 쭉 올라가는 꿈', '빠르게 인정받고 오릅니다.'],
        ['엘리베이터가 뚝 떨어지는 꿈', '무리한 계획을 조심하세요.'],
        ['엘리베이터에 갇히는 꿈', '잠시 정체, 조급해하지 마세요.'],
        ['문이 열리지 않는 꿈', '다른 길을 찾아보세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy thang máy', keywords: ['thang máy', 'kẹt thang máy', 'thang máy đi lên'],
      summary: 'Thang máy là lên xuống nhanh — địa vị, vận số thay đổi gấp. Đi lên thẳng là nhanh được công nhận.',
      korea: 'Người Hàn cho rằng thang máy lên thẳng là nhanh được công nhận nhờ thăng chức, thành tích; rơi đột ngột là cẩn thận kỳ vọng quá mức, kế hoạch quá sức; kẹt trong thang máy là việc tạm đứng, đừng nóng vội; cửa không mở là thử tìm đường khác (cầu thang).',
      vietnam: 'Người Việt giải mơ thấy thang máy là thay đổi địa vị: đi lên là thăng chức, đi xuống là cẩn thận tổn thất.',
      cases: [
        ['Mơ thang máy đi lên', 'Nhanh được công nhận.'],
        ['Mơ thang máy rơi', 'Cẩn thận kế hoạch quá sức.'],
        ['Mơ kẹt thang máy', 'Tạm đứng, đừng nóng vội.'],
        ['Mơ cửa thang máy không mở', 'Tìm đường khác.'],
      ],
    },
  },
  {
    slug: 'funeral', category: 'situation', tone: 'good', emoji: '⚱️',
    ko: {
      name: '장례식 꿈', keywords: ['장례식', '장례식 꿈', '관', '상여', '상복'],
      summary: '장례식 꿈은 대표적인 반대해몽으로, 걱정이 끝나고 새로운 시작과 재물이 오는 길몽으로 봅니다.',
      korea: '남의 장례식에 가면 오래된 걱정이 끝나고 막혔던 일이 풀린다고 봅니다. 관을 보거나 관에 돈이 들어 있으면 관(官)과 소리가 같아 벼슬·재물운으로 풀고, 상복을 입으면 집안에 경사나 이익이 생깁니다. 다만 장례식에서 크게 슬퍼하면 마음에 쌓인 감정을 풀 때라는 뜻입니다. 내가 죽는 꿈은 "내가 죽는 꿈"을 참고하세요.',
      vietnam: '베트남에서도 장례식(đám tang) 꿈은 흔히 반대로 풀어 재물운과 행운이 온다고 봅니다. 관(quan tài)은 "quan"(벼슬)과 "tài"(재물)가 합쳐진 말이라 승진과 재물을 뜻한다는 풀이가 유명합니다.',
      cases: [
        ['남의 장례식에 가는 꿈', '오랜 걱정이 끝나고 일이 풀립니다.'],
        ['관을 보는 꿈', '벼슬·재물운으로 풉니다.'],
        ['상복을 입는 꿈', '집안에 경사나 이익이 생깁니다.'],
        ['장례식에서 크게 우는 꿈', '쌓인 감정을 풀 때입니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đám tang', keywords: ['đám tang', 'quan tài', 'đám ma', 'tang lễ', 'áo tang'],
      summary: 'Đám tang thường được giải ngược: hết lo âu, khởi đầu mới và có tiền của.',
      korea: 'Người Hàn cho rằng đi đám tang người khác là nỗi lo lâu nay chấm dứt, việc bế tắc được gỡ; thấy quan tài hay tiền trong quan tài là vận quan chức, tiền của (chữ “quan” 棺 đồng âm với “quan” 官 trong tiếng Hàn); mặc áo tang là nhà có hỷ sự, có lợi; khóc nhiều ở đám tang là nên giải tỏa cảm xúc dồn nén.',
      vietnam: 'Người Việt cũng hay giải ngược: mơ thấy đám tang là có lộc, gặp may. Cách giải nổi tiếng: “quan tài” là “quan” (chức) và “tài” (tiền) — thăng tiến, phát tài.',
      cases: [
        ['Mơ đi đám tang', 'Hết lo, việc được gỡ.'],
        ['Mơ thấy quan tài', 'Thăng quan, phát tài.'],
        ['Mơ mặc áo tang', 'Nhà có hỷ sự, có lợi.'],
        ['Mơ khóc ở đám tang', 'Giải tỏa cảm xúc dồn nén.'],
      ],
    },
  },
  {
    slug: 'makeup', category: 'situation', tone: 'mixed', emoji: '💄',
    ko: {
      name: '화장하는 꿈', keywords: ['화장', '화장하는 꿈', '립스틱', '메이크업', '화장이 지워지는 꿈'],
      summary: '화장은 나를 꾸미고 보여 주고 싶은 마음, 자신감을 뜻합니다. 곱게 화장하면 좋은 자리에 나서는 꿈입니다.',
      korea: '곱게 화장하면 중요한 자리나 만남에서 좋은 인상을 남기고 인기를 얻는다고 봅니다. 화장이 번지거나 지워지면 감추고 싶은 본모습이 드러날까 걱정하는 마음이니 솔직함이 오히려 도움이 되고, 진한 화장은 지나친 꾸밈을 조심하라는 뜻입니다. 남에게 화장을 해 주면 그 사람을 돕게 됩니다.',
      vietnam: '베트남에서 화장(trang điểm) 꿈은 새로운 만남과 매력을 뜻하지만, 화장이 지워지면 비밀이 드러날 수 있다고 봅니다.',
      cases: [
        ['곱게 화장하는 꿈', '좋은 인상을 남기고 인기를 얻습니다.'],
        ['화장이 번지는 꿈', '솔직함이 오히려 도움이 됩니다.'],
        ['진한 화장을 하는 꿈', '지나친 꾸밈을 조심하세요.'],
        ['남에게 화장해 주는 꿈', '그 사람을 돕게 됩니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy trang điểm', keywords: ['trang điểm', 'son môi', 'đánh son', 'lớp trang điểm'],
      summary: 'Trang điểm là mong muốn chăm chút, thể hiện bản thân và sự tự tin. Trang điểm đẹp là sắp xuất hiện ở dịp tốt.',
      korea: 'Người Hàn cho rằng trang điểm đẹp là gây ấn tượng tốt ở cuộc gặp quan trọng, được yêu mến; lớp trang điểm lem, trôi là lo con người thật bị lộ — thành thật lại có lợi; trang điểm đậm là cẩn thận phô trương; trang điểm cho người khác là sẽ giúp người đó.',
      vietnam: 'Người Việt giải mơ thấy trang điểm là gặp gỡ mới, sức hút; lớp phấn trôi là bí mật có thể lộ.',
      cases: [
        ['Mơ trang điểm đẹp', 'Gây ấn tượng tốt.'],
        ['Mơ lớp trang điểm bị lem', 'Thành thật lại có lợi.'],
        ['Mơ trang điểm đậm', 'Cẩn thận phô trương.'],
        ['Mơ trang điểm cho người khác', 'Sẽ giúp người đó.'],
      ],
    },
  },
  {
    slug: 'bicycle', category: 'situation', tone: 'good', emoji: '🚲',
    ko: {
      name: '자전거 꿈', keywords: ['자전거', '자전거 타는 꿈', '자전거 꿈'],
      summary: '자전거는 스스로의 힘으로 나아가는 균형과 노력을 뜻합니다. 씽씽 달리면 노력한 만큼 앞으로 나아갑니다.',
      korea: '자전거를 시원하게 타고 달리면 남에게 기대지 않고 내 힘으로 일이 진척된다고 봅니다. 오르막을 힘들게 오르면 지금의 수고가 곧 보상받고, 누군가를 뒤에 태우면 그 사람과 함께 걸어갈 일이 생깁니다. 자전거에서 넘어지면 일과 생활의 균형을 다시 잡으라는 꿈입니다.',
      vietnam: '베트남에서 자전거(xe đạp) 꿈은 소박한 노력과 학생 시절의 추억을 뜻합니다. 함께 타면 순수한 사랑을 뜻하기도 합니다.',
      cases: [
        ['자전거로 씽씽 달리는 꿈', '내 힘으로 일이 진척됩니다.'],
        ['오르막을 오르는 꿈', '지금의 수고가 곧 보상받습니다.'],
        ['누군가를 뒤에 태우는 꿈', '그 사람과 함께할 일이 생깁니다.'],
        ['자전거에서 넘어지는 꿈', '균형을 다시 잡으세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy xe đạp', keywords: ['xe đạp', 'đạp xe', 'ngã xe đạp'],
      summary: 'Xe đạp là thăng bằng và nỗ lực bằng sức mình. Đạp xe vun vút là cố gắng bao nhiêu tiến bấy nhiêu.',
      korea: 'Người Hàn cho rằng đạp xe thoải mái là việc tiến triển bằng sức mình, không dựa ai; đạp lên dốc vất vả là công sức sắp được đền đáp; chở ai phía sau là sẽ đồng hành cùng người đó; ngã xe đạp là nên cân bằng lại công việc và cuộc sống.',
      vietnam: 'Người Việt giải mơ thấy xe đạp là nỗ lực giản dị, kỷ niệm thời học trò; đạp xe cùng ai là tình cảm trong sáng.',
      cases: [
        ['Mơ đạp xe vun vút', 'Tiến triển bằng sức mình.'],
        ['Mơ đạp xe lên dốc', 'Công sức sắp được đền đáp.'],
        ['Mơ chở ai sau xe đạp', 'Đồng hành cùng người đó.'],
        ['Mơ ngã xe đạp', 'Cân bằng lại cuộc sống.'],
      ],
    },
  },
  {
    slug: 'interview', category: 'situation', tone: 'mixed', emoji: '💼',
    ko: {
      name: '면접 꿈', keywords: ['면접', '면접 보는 꿈', '취업', '면접 꿈'],
      summary: '면접 꿈은 평가받는 불안과 새로운 기회를 함께 비춥니다. 면접을 잘 보면 실제로 좋은 소식이 가까워집니다.',
      korea: '면접에서 자신 있게 대답하면 준비한 만큼 좋은 결과가 오고, 면접관이 웃으면 윗사람의 호감을 얻는다고 봅니다. 대답을 못 하거나 지각하면 준비가 부족하다는 마음의 신호이니 점검하라는 뜻이고, 내가 면접관이 되면 사람을 고르는 책임이 생깁니다.',
      vietnam: '베트남에서 면접(phỏng vấn) 꿈은 일자리와 기회의 변화를 뜻합니다. 면접에 붙으면 실제로 좋은 소식이 온다고 봅니다.',
      cases: [
        ['면접에서 자신 있게 답하는 꿈', '준비한 만큼 좋은 결과가 옵니다.'],
        ['면접관이 웃는 꿈', '윗사람의 호감을 얻습니다.'],
        ['대답을 못 하는 꿈', '준비를 한 번 더 점검하세요.'],
        ['내가 면접관이 되는 꿈', '사람을 고르는 책임이 생깁니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đi phỏng vấn', keywords: ['phỏng vấn', 'đi phỏng vấn', 'xin việc'],
      summary: 'Mơ đi phỏng vấn phản ánh nỗi lo bị đánh giá và cơ hội mới. Phỏng vấn trôi chảy là tin vui đang đến gần.',
      korea: 'Người Hàn cho rằng trả lời tự tin khi phỏng vấn là chuẩn bị bao nhiêu kết quả tốt bấy nhiêu; người phỏng vấn cười là được bề trên có thiện cảm; không trả lời được hay đến muộn là tín hiệu chuẩn bị chưa đủ; mình làm người phỏng vấn là có trách nhiệm chọn người.',
      vietnam: 'Người Việt giải mơ đi phỏng vấn là thay đổi công việc, cơ hội; mơ đậu phỏng vấn là có tin vui thật.',
      cases: [
        ['Mơ phỏng vấn trôi chảy', 'Có kết quả tốt.'],
        ['Mơ người phỏng vấn cười', 'Được bề trên thiện cảm.'],
        ['Mơ không trả lời được', 'Chuẩn bị thêm.'],
        ['Mơ mình phỏng vấn người khác', 'Có trách nhiệm chọn người.'],
      ],
    },
  },
  {
    slug: 'quitting', category: 'situation', tone: 'mixed', emoji: '📦',
    ko: {
      name: '퇴사·이직 꿈', keywords: ['퇴사', '이직', '회사 그만두는 꿈', '사표', '해고'],
      summary: '퇴사 꿈은 변화를 바라는 마음과 지친 몸의 신호입니다. 시원하게 사표를 내면 새 출발의 기회가 다가옵니다.',
      korea: '사표를 내고 홀가분하면 지금의 답답함을 벗어날 변화와 새 출발이 다가온다고 봅니다. 해고당하면 반대로 지금 자리를 지키게 된다는 풀이도 있지만, 무엇보다 피로가 쌓였다는 신호이니 쉬어 가세요. 새 회사에 출근하면 이직이나 새 역할의 기회가 생깁니다.',
      vietnam: '베트남에서 직장을 그만두는 꿈(nghỉ việc)은 변화를 원하는 마음을 뜻하며, 새 직장으로 옮기면 더 좋은 기회가 온다고 봅니다.',
      cases: [
        ['사표를 내고 홀가분한 꿈', '변화와 새 출발이 다가옵니다.'],
        ['해고당하는 꿈', '피로가 쌓였습니다. 쉬어 가세요.'],
        ['새 회사에 출근하는 꿈', '이직이나 새 역할의 기회가 생깁니다.'],
        ['퇴사를 말리는 꿈', '지금 자리에서 인정받고 있습니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy nghỉ việc', keywords: ['nghỉ việc', 'bỏ việc', 'bị đuổi việc', 'chuyển việc'],
      summary: 'Mơ nghỉ việc là mong muốn thay đổi và tín hiệu cơ thể mệt mỏi. Nộp đơn nghỉ nhẹ nhõm là cơ hội khởi đầu mới đang tới.',
      korea: 'Người Hàn cho rằng nộp đơn nghỉ việc và thấy nhẹ nhõm là sắp có thay đổi, khởi đầu mới; bị đuổi việc có khi được giải ngược là giữ được chỗ, nhưng trước hết là dấu hiệu mệt mỏi, hãy nghỉ ngơi; đi làm ở công ty mới là có cơ hội chuyển việc, vai trò mới; được giữ lại khi xin nghỉ là đang được công nhận.',
      vietnam: 'Người Việt giải mơ nghỉ việc là muốn thay đổi; mơ chuyển sang chỗ làm mới là có cơ hội tốt hơn.',
      cases: [
        ['Mơ nghỉ việc nhẹ nhõm', 'Khởi đầu mới đang tới.'],
        ['Mơ bị đuổi việc', 'Đang mệt, hãy nghỉ ngơi.'],
        ['Mơ đi làm chỗ mới', 'Có cơ hội chuyển việc.'],
        ['Mơ được giữ lại', 'Đang được công nhận.'],
      ],
    },
  },
  {
    slug: 'promotion', category: 'situation', tone: 'good', emoji: '📈',
    ko: {
      name: '승진 꿈', keywords: ['승진', '승진 꿈', '진급', '임명'],
      summary: '승진 꿈은 인정받고 싶은 마음과 실제 지위 상승의 징조입니다. 축하를 받으면 노력이 결실을 맺는 꿈입니다.',
      korea: '승진해서 축하를 받으면 그동안의 노력이 인정받고 좋은 평가나 보상이 따른다고 봅니다. 높은 자리에 앉았는데 불안하면 책임이 커질 것을 걱정하는 마음이고, 남이 승진하면 나에게도 곧 기회가 오니 준비하라는 뜻입니다. 임명장을 받으면 문서운이 좋습니다.',
      vietnam: '베트남에서 승진(thăng chức) 꿈은 실제 직장운의 상승과 귀인의 도움을 뜻합니다.',
      cases: [
        ['승진해서 축하받는 꿈', '노력이 인정받고 보상이 따릅니다.'],
        ['높은 자리가 불안한 꿈', '커질 책임을 미리 준비하세요.'],
        ['남이 승진하는 꿈', '나에게도 곧 기회가 옵니다.'],
        ['임명장을 받는 꿈', '문서운이 좋습니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy thăng chức', keywords: ['thăng chức', 'lên chức', 'được bổ nhiệm'],
      summary: 'Mơ thăng chức là mong được công nhận và cũng là điềm địa vị đi lên. Được chúc mừng là công sức thành quả.',
      korea: 'Người Hàn cho rằng được thăng chức và chúc mừng là công sức được ghi nhận, có đánh giá, phần thưởng tốt; ngồi ghế cao mà bất an là lo trách nhiệm lớn hơn; người khác thăng chức là mình cũng sắp có cơ hội; nhận quyết định bổ nhiệm là vận giấy tờ tốt.',
      vietnam: 'Người Việt giải mơ thăng chức là vận công việc đi lên, có quý nhân giúp đỡ.',
      cases: [
        ['Mơ được thăng chức', 'Công sức được ghi nhận.'],
        ['Mơ ngồi ghế cao mà lo', 'Chuẩn bị cho trách nhiệm.'],
        ['Mơ người khác thăng chức', 'Mình sắp có cơ hội.'],
        ['Mơ nhận quyết định bổ nhiệm', 'Vận giấy tờ tốt.'],
      ],
    },
  },
  {
    slug: 'contract', category: 'situation', tone: 'good', emoji: '📝',
    ko: {
      name: '계약·도장 꿈', keywords: ['계약', '도장', '도장 찍는 꿈', '계약서', '서명'],
      summary: '한국에서 도장을 찍는 꿈은 대표적인 문서운 길몽입니다. 계약서에 서명하면 집·일·인연이 확정되는 꿈입니다.',
      korea: '계약서에 도장을 찍거나 서명하면 집 계약, 취업, 혼인처럼 중요한 일이 확정되고 문서로 이익을 본다고 봅니다. 도장이 선명하게 찍히면 일이 깔끔하게 마무리되고, 도장이 번지거나 잃어버리면 계약 조건과 서류를 꼼꼼히 확인하라는 뜻입니다. 남에게 도장을 맡기면 보증이나 돈 거래를 조심하세요.',
      vietnam: '베트남에서 계약(hợp đồng) 꿈은 사업과 일의 성사를 뜻합니다. 서명하는 꿈은 약속이 이루어진다고 봅니다.',
      cases: [
        ['계약서에 도장을 찍는 꿈', '중요한 일이 확정되고 문서로 이익을 봅니다.'],
        ['도장이 선명하게 찍히는 꿈', '일이 깔끔하게 마무리됩니다.'],
        ['도장을 잃어버리는 꿈', '계약 조건을 꼼꼼히 확인하세요.'],
        ['남에게 도장을 맡기는 꿈', '보증과 돈 거래를 조심하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy ký hợp đồng', keywords: ['hợp đồng', 'ký hợp đồng', 'đóng dấu', 'chữ ký'],
      summary: 'Với người Hàn, mơ đóng dấu là điềm tốt về giấy tờ. Ký hợp đồng là nhà cửa, công việc, nhân duyên được xác lập.',
      korea: 'Người Hàn cho rằng đóng dấu, ký hợp đồng là việc quan trọng như mua nhà, xin việc, kết hôn được chốt, có lợi nhờ giấy tờ; dấu in rõ nét là việc kết thúc gọn gàng; dấu nhòe hay mất con dấu là kiểm tra kỹ điều khoản; giao con dấu cho người khác là cẩn thận bảo lãnh, vay mượn.',
      vietnam: 'Người Việt giải mơ ký hợp đồng là làm ăn thành công; ký tên là lời hứa thành sự thật.',
      cases: [
        ['Mơ ký hợp đồng, đóng dấu', 'Việc lớn được chốt, có lợi.'],
        ['Mơ dấu in rõ nét', 'Việc kết thúc gọn gàng.'],
        ['Mơ mất con dấu', 'Kiểm tra kỹ điều khoản.'],
        ['Mơ giao dấu cho người khác', 'Cẩn thận bảo lãnh, vay mượn.'],
      ],
    },
  },
  {
    slug: 'debt', category: 'situation', tone: 'mixed', emoji: '🧾',
    ko: {
      name: '빚 꿈', keywords: ['빚', '빚 꿈', '빚 갚는 꿈', '대출', '돈 빌리는 꿈'],
      summary: '빚 꿈은 마음의 부담과 책임감을 비춥니다. 빚을 다 갚으면 오래된 짐을 내려놓는 길몽입니다.',
      korea: '빚을 다 갚으면 오래된 걱정과 책임에서 벗어나 마음이 가벼워진다고 봅니다. 빚 독촉을 받으면 미뤄 둔 약속이나 일을 정리하라는 뜻이고, 남에게 돈을 빌려주면 베푼 만큼 돌아오지만 큰 금액이면 신중하라는 꿈입니다. 남이 내 빚을 갚아 주면 뜻밖의 도움을 받습니다.',
      vietnam: '베트남에서 빚(nợ) 꿈은 갚지 못한 마음의 빚, 인정의 빚을 뜻하기도 합니다. 빚을 갚으면 근심이 사라집니다.',
      cases: [
        ['빚을 다 갚는 꿈', '오래된 짐을 내려놓습니다.'],
        ['빚 독촉을 받는 꿈', '미뤄 둔 약속을 정리하세요.'],
        ['남에게 돈을 빌려주는 꿈', '큰돈 거래는 신중하세요.'],
        ['남이 내 빚을 갚아 주는 꿈', '뜻밖의 도움을 받습니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy nợ nần', keywords: ['nợ', 'trả nợ', 'đòi nợ', 'vay tiền', 'nợ nần'],
      summary: 'Mơ thấy nợ phản ánh gánh nặng trong lòng và trách nhiệm. Trả hết nợ là đặt xuống được gánh nặng lâu năm.',
      korea: 'Người Hàn cho rằng trả hết nợ là thoát khỏi lo âu, trách nhiệm lâu năm, lòng nhẹ nhõm; bị đòi nợ là nên giải quyết lời hứa, việc còn để đó; cho người khác vay là cho đi thì nhận lại nhưng số tiền lớn phải thận trọng; người khác trả nợ thay mình là có người giúp bất ngờ.',
      vietnam: 'Người Việt giải mơ thấy nợ còn là món nợ ân tình chưa trả; trả được nợ là hết lo âu.',
      cases: [
        ['Mơ trả hết nợ', 'Đặt xuống gánh nặng.'],
        ['Mơ bị đòi nợ', 'Giải quyết lời hứa còn treo.'],
        ['Mơ cho người khác vay', 'Thận trọng với khoản lớn.'],
        ['Mơ được trả nợ thay', 'Có người giúp bất ngờ.'],
      ],
    },
  },
  {
    slug: 'war', category: 'situation', tone: 'mixed', emoji: '⚔️',
    ko: {
      name: '전쟁 꿈', keywords: ['전쟁', '전쟁 꿈', '폭탄', '피난'],
      summary: '전쟁 꿈은 큰 갈등이나 변화를 앞둔 긴장을 비춥니다. 전쟁에서 이기면 어려운 싸움을 이겨 내는 꿈입니다.',
      korea: '전쟁에서 싸워 이기면 경쟁이나 갈등에서 승리하고 큰 고비를 넘긴다고 봅니다. 피난을 가면 지금 상황에서 한발 물러나 안전을 챙기라는 뜻이고, 폭탄이 터지면 쌓인 감정이나 문제가 한꺼번에 드러날 수 있으니 미리 풀어 두세요. 전쟁이 끝나는 꿈은 오래된 다툼이 마무리됩니다.',
      vietnam: '베트남에서 전쟁(chiến tranh) 꿈은 가족이나 직장의 갈등을 뜻하며, 전쟁이 끝나면 평화와 화해가 온다고 봅니다.',
      cases: [
        ['전쟁에서 이기는 꿈', '경쟁에서 이기고 고비를 넘깁니다.'],
        ['피난 가는 꿈', '한발 물러나 안전을 챙기세요.'],
        ['폭탄이 터지는 꿈', '쌓인 감정을 미리 풀어 두세요.'],
        ['전쟁이 끝나는 꿈', '오래된 다툼이 마무리됩니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy chiến tranh', keywords: ['chiến tranh', 'đánh trận', 'bom nổ', 'chạy loạn'],
      summary: 'Mơ thấy chiến tranh phản ánh căng thẳng trước xung đột hay thay đổi lớn. Thắng trận là vượt qua cuộc chiến khó khăn.',
      korea: 'Người Hàn cho rằng đánh thắng trận là thắng trong cạnh tranh, xung đột, qua cửa ải lớn; chạy loạn là nên lùi một bước, giữ an toàn; bom nổ là cảm xúc, vấn đề dồn nén có thể bùng ra cùng lúc — hãy giải tỏa trước; chiến tranh kết thúc là tranh chấp lâu năm khép lại.',
      vietnam: 'Người Việt giải mơ thấy chiến tranh là mâu thuẫn trong nhà hay nơi làm việc; chiến tranh kết thúc là hòa bình, hòa giải.',
      cases: [
        ['Mơ thắng trận', 'Thắng trong cạnh tranh.'],
        ['Mơ chạy loạn', 'Lùi một bước, giữ an toàn.'],
        ['Mơ bom nổ', 'Giải tỏa cảm xúc trước.'],
        ['Mơ chiến tranh kết thúc', 'Tranh chấp khép lại.'],
      ],
    },
  },
  {
    slug: 'party', category: 'situation', tone: 'good', emoji: '🎉',
    ko: {
      name: '잔치·파티 꿈', keywords: ['잔치', '파티', '잔칫집', '연회', '잔치 꿈'],
      summary: '잔치는 경사와 사람이 모이는 기쁨을 뜻합니다. 잔칫상이 푸짐하면 집안에 좋은 일이 연달아 생기는 꿈입니다.',
      korea: '푸짐한 잔칫상에 사람들이 모이면 집안에 경사가 생기고 인복이 늘어난다고 봅니다. 내가 잔치를 열면 내 일로 사람들이 축하할 일이 생기고, 잔치에 초대받으면 좋은 인연을 만납니다. 잔치가 끝나 허전하면 지나친 지출을 조심하라는 뜻입니다.',
      vietnam: '베트남에서 잔치(tiệc, đám cỗ) 꿈은 경사와 풍요를 뜻합니다. 잔치에서 배불리 먹으면 먹을 복과 재물운이 있습니다.',
      cases: [
        ['푸짐한 잔칫상 꿈', '경사가 생기고 인복이 늘어납니다.'],
        ['내가 잔치를 여는 꿈', '사람들이 축하할 일이 생깁니다.'],
        ['잔치에 초대받는 꿈', '좋은 인연을 만납니다.'],
        ['잔치가 끝나 허전한 꿈', '지나친 지출을 조심하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy tiệc, ăn cỗ', keywords: ['tiệc', 'ăn cỗ', 'đám cỗ', 'bữa tiệc', 'dự tiệc'],
      summary: 'Tiệc tùng là hỷ sự và niềm vui sum họp. Mâm cỗ thịnh soạn là nhà có chuyện vui nối tiếp.',
      korea: 'Người Hàn cho rằng mâm cỗ thịnh soạn, đông người là nhà có hỷ sự, nhân duyên tốt; mình mở tiệc là có việc khiến mọi người chúc mừng; được mời dự tiệc là gặp người tốt; tiệc tàn mà thấy trống trải là cẩn thận chi tiêu quá đà.',
      vietnam: 'Người Việt giải mơ ăn cỗ, dự tiệc là hỷ sự, sung túc; ăn no ở tiệc là có lộc ăn, lộc tiền.',
      cases: [
        ['Mơ mâm cỗ thịnh soạn', 'Nhà có hỷ sự.'],
        ['Mơ mình mở tiệc', 'Có việc được chúc mừng.'],
        ['Mơ được mời dự tiệc', 'Gặp người tốt.'],
        ['Mơ tiệc tàn trống trải', 'Cẩn thận chi tiêu.'],
      ],
    },
  },
  {
    slug: 'birthday', category: 'situation', tone: 'good', emoji: '🎂',
    ko: {
      name: '생일 꿈', keywords: ['생일', '생일 케이크', '생일 꿈', '생일 파티'],
      summary: '생일 꿈은 새로운 출발과 축하받을 일을 뜻합니다. 케이크 촛불을 끄면 소원이 이루어지는 꿈입니다.',
      korea: '생일 축하를 받으면 주변의 사랑을 확인하고 기쁜 소식이 온다고 봅니다. 케이크 촛불을 한 번에 끄면 바라던 일이 이루어지고, 생일을 잊어버리면 바쁜 일상 속에서 나 자신을 돌보라는 뜻입니다. 남의 생일을 챙기면 관계가 깊어집니다.',
      vietnam: '베트남에서 생일(sinh nhật) 꿈은 새 출발과 행운, 가족의 사랑을 뜻합니다.',
      cases: [
        ['생일 축하를 받는 꿈', '사랑을 확인하고 기쁜 소식이 옵니다.'],
        ['촛불을 한 번에 끄는 꿈', '바라던 일이 이루어집니다.'],
        ['생일을 잊어버리는 꿈', '나 자신을 돌보세요.'],
        ['남의 생일을 챙기는 꿈', '관계가 깊어집니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy sinh nhật', keywords: ['sinh nhật', 'bánh sinh nhật', 'thổi nến'],
      summary: 'Mơ sinh nhật là khởi đầu mới và chuyện đáng mừng. Thổi nến bánh kem là ước nguyện thành.',
      korea: 'Người Hàn cho rằng được chúc mừng sinh nhật là thấy được tình thương quanh mình, có tin vui; thổi tắt nến một lần là điều mong muốn thành; quên sinh nhật mình là giữa bận rộn hãy chăm sóc bản thân; nhớ sinh nhật người khác là quan hệ sâu thêm.',
      vietnam: 'Người Việt giải mơ thấy sinh nhật là khởi đầu mới, may mắn, tình thương gia đình.',
      cases: [
        ['Mơ được chúc mừng sinh nhật', 'Có tin vui.'],
        ['Mơ thổi tắt nến một lần', 'Ước nguyện thành.'],
        ['Mơ quên sinh nhật', 'Chăm sóc bản thân.'],
        ['Mơ tổ chức sinh nhật cho người khác', 'Quan hệ sâu thêm.'],
      ],
    },
  },
  {
    slug: 'graduation', category: 'situation', tone: 'good', emoji: '🎓',
    ko: {
      name: '졸업 꿈', keywords: ['졸업', '졸업식', '학사모', '졸업 꿈'],
      summary: '졸업은 한 단계의 성공적인 마무리와 새 출발을 뜻합니다. 학사모를 던지면 노력이 결실을 맺는 길몽입니다.',
      korea: '졸업식에서 학위를 받으면 하던 일을 잘 마무리하고 다음 단계로 나아간다고 봅니다. 학사모를 던지면 오랜 노력이 결실을 맺고, 졸업을 못 하면 마무리 짓지 못한 일이 마음에 걸린다는 뜻이니 하나씩 끝내세요. 가족이 졸업하면 집안에 경사가 생깁니다.',
      vietnam: '베트남에서 졸업(tốt nghiệp) 꿈은 학업과 일의 성취, 새로운 시작을 뜻합니다.',
      cases: [
        ['졸업장을 받는 꿈', '한 단계를 마무리하고 나아갑니다.'],
        ['학사모를 던지는 꿈', '오랜 노력이 결실을 맺습니다.'],
        ['졸업을 못 하는 꿈', '미뤄 둔 일을 하나씩 끝내세요.'],
        ['가족이 졸업하는 꿈', '집안에 경사가 생깁니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy tốt nghiệp', keywords: ['tốt nghiệp', 'lễ tốt nghiệp', 'nhận bằng'],
      summary: 'Tốt nghiệp là khép lại một chặng thành công và khởi đầu mới. Tung mũ cử nhân là công sức thành quả.',
      korea: 'Người Hàn cho rằng nhận bằng ở lễ tốt nghiệp là hoàn thành tốt việc đang làm, sang chặng mới; tung mũ là nỗ lực lâu năm có kết quả; không tốt nghiệp được là còn việc chưa xong vướng trong lòng, hãy làm xong từng việc; người nhà tốt nghiệp là nhà có hỷ sự.',
      vietnam: 'Người Việt giải mơ tốt nghiệp là thành tựu học hành, công việc và khởi đầu mới.',
      cases: [
        ['Mơ nhận bằng tốt nghiệp', 'Xong một chặng, sang chặng mới.'],
        ['Mơ tung mũ cử nhân', 'Nỗ lực có kết quả.'],
        ['Mơ không tốt nghiệp được', 'Làm xong việc còn dở.'],
        ['Mơ người nhà tốt nghiệp', 'Nhà có hỷ sự.'],
      ],
    },
  },
  {
    slug: 'hiding', category: 'situation', tone: 'mixed', emoji: '🙈',
    ko: {
      name: '숨는 꿈', keywords: ['숨는 꿈', '숨바꼭질', '숨어 있는 꿈', '도망쳐 숨는 꿈'],
      summary: '숨는 꿈은 피하고 싶은 일이나 드러내기 싫은 비밀을 비춥니다. 무사히 숨으면 잠시 쉬어 갈 피난처가 생깁니다.',
      korea: '누군가를 피해 숨으면 지금 마주하기 싫은 일이 있다는 마음의 신호이니, 작은 것부터 정면으로 해결해 보세요. 들키지 않고 무사히 숨으면 잠시 쉬어 갈 곳이나 도와줄 사람이 생기고, 숨었다가 들키면 감춘 일이 드러날 수 있으니 먼저 털어놓는 것이 낫습니다. 숨바꼭질은 사람들과의 즐거운 관계를 뜻합니다.',
      vietnam: '베트남에서 숨는 꿈(trốn)은 걱정과 비밀을 뜻하며, 숨바꼭질(trốn tìm)은 어린 시절의 추억과 순수한 관계를 뜻합니다.',
      cases: [
        ['누군가를 피해 숨는 꿈', '작은 것부터 정면으로 해결하세요.'],
        ['무사히 숨는 꿈', '쉬어 갈 곳이나 도와줄 사람이 생깁니다.'],
        ['숨었다가 들키는 꿈', '먼저 털어놓는 것이 낫습니다.'],
        ['숨바꼭질하는 꿈', '사람들과 즐거운 관계를 뜻합니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy trốn', keywords: ['trốn', 'đi trốn', 'trốn tìm', 'lẩn trốn'],
      summary: 'Mơ đi trốn phản ánh điều muốn né tránh hay bí mật không muốn lộ. Trốn an toàn là có chốn nghỉ chân tạm thời.',
      korea: 'Người Hàn cho rằng trốn ai đó là đang có việc không muốn đối mặt — hãy giải quyết từ việc nhỏ; trốn an toàn không bị phát hiện là có nơi nghỉ chân, người giúp; trốn rồi bị phát hiện là chuyện giấu có thể lộ, nên tự nói ra trước; chơi trốn tìm là quan hệ vui vẻ.',
      vietnam: 'Người Việt giải mơ đi trốn là lo âu, bí mật; mơ chơi trốn tìm là kỷ niệm tuổi thơ, quan hệ trong sáng.',
      cases: [
        ['Mơ trốn ai đó', 'Giải quyết từ việc nhỏ.'],
        ['Mơ trốn an toàn', 'Có chốn nghỉ, người giúp.'],
        ['Mơ trốn bị phát hiện', 'Nên tự nói ra trước.'],
        ['Mơ chơi trốn tìm', 'Quan hệ vui vẻ.'],
      ],
    },
  },
];
