import type { Dream } from './types';

export const SITUATION_DREAMS_5: Dream[] = [
  {
    slug: 'market', category: 'situation', tone: 'good', emoji: '🏪',
    ko: {
      name: '시장 꿈', keywords: ['시장', '재래시장', '장터', '장 보는 꿈', '시장 꿈'],
      summary: '북적이는 시장은 활발한 거래와 사람 운을 뜻합니다. 시장에서 물건을 잘 사면 실속 있는 기회를 잡는 꿈입니다.',
      korea: '사람들로 북적이는 시장을 구경하면 장사와 거래가 활발해지고 새 인맥이 생긴다고 봅니다. 시장에서 마음에 드는 물건을 싸게 사면 실속 있는 기회를 잡고, 내가 물건을 팔아 손님이 몰리면 수입이 늘어납니다. 텅 빈 시장은 계획을 다시 다듬으라는 뜻입니다.',
      vietnam: '베트남 사람에게 시장(chợ), 특히 설 대목장(chợ Tết)은 풍요와 새해 복을 상징합니다. 시장에서 장을 보는 꿈은 살림이 넉넉해지고 집안에 기쁜 일이 생기는 꿈입니다.',
      cases: [
        ['북적이는 시장 꿈', '거래가 활발해지고 인맥이 생깁니다.'],
        ['시장에서 물건을 싸게 사는 꿈', '실속 있는 기회를 잡습니다.'],
        ['시장에서 물건을 파는 꿈', '수입이 늘어납니다.'],
        ['텅 빈 시장 꿈', '계획을 다시 다듬으세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đi chợ', keywords: ['chợ', 'đi chợ', 'chợ Tết', 'họp chợ', 'bán hàng ở chợ'],
      summary: 'Chợ đông đúc là buôn bán thuận lợi và vận nhân duyên. Mua được món hời ở chợ là nắm cơ hội có lợi.',
      korea: 'Người Hàn cho rằng dạo chợ đông người là việc mua bán sôi động, có thêm mối quen; mua được món ưng ý giá rẻ là nắm cơ hội thực chất; mình bán hàng đông khách là thu nhập tăng; chợ vắng tanh là nên xem lại kế hoạch.',
      vietnam: 'Với người Việt, chợ — nhất là chợ Tết — là biểu tượng sung túc, phúc đầu năm. Mơ đi chợ là nhà cửa no đủ, có chuyện vui.',
      cases: [
        ['Mơ chợ đông người', 'Buôn bán sôi động, thêm mối quen.'],
        ['Mơ mua được món hời', 'Nắm cơ hội có lợi.'],
        ['Mơ bán hàng ở chợ', 'Thu nhập tăng.'],
        ['Mơ chợ vắng tanh', 'Xem lại kế hoạch.'],
      ],
    },
  },
  {
    slug: 'glasses', category: 'situation', tone: 'mixed', emoji: '👓',
    ko: {
      name: '안경 꿈', keywords: ['안경', '선글라스', '안경 꿈', '안경이 깨지는 꿈'],
      summary: '안경은 세상을 보는 눈과 판단력을 뜻합니다. 새 안경을 쓰면 시야가 넓어지고, 안경이 깨지면 오해를 조심하라는 꿈입니다.',
      korea: '새 안경을 맞춰 쓰면 상황을 또렷하게 보게 되어 좋은 판단을 내린다고 봅니다. 안경이 깨지거나 잃어버리면 믿던 생각이 흔들리거나 오해가 생길 수 있으니 확인을 거듭하라는 뜻이고, 선글라스를 쓰면 속마음을 감추고 싶은 마음을 비춥니다. 남에게 안경을 빌려주면 내 조언이 도움이 됩니다.',
      vietnam: '베트남에서 안경(kính mắt) 꿈은 사물을 정확히 보는 지혜를 뜻합니다. 안경이 흐려지면 일이 불분명하니 서두르지 말라는 뜻으로 봅니다.',
      cases: [
        ['새 안경을 쓰는 꿈', '시야가 넓어지고 판단이 좋아집니다.'],
        ['안경이 깨지는 꿈', '오해가 없도록 다시 확인하세요.'],
        ['선글라스를 쓰는 꿈', '속마음을 너무 감추지는 마세요.'],
        ['안경을 빌려주는 꿈', '내 조언이 남에게 도움이 됩니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy kính mắt', keywords: ['kính mắt', 'đeo kính', 'kính vỡ', 'kính râm'],
      summary: 'Kính là cách nhìn đời và khả năng phán đoán. Đeo kính mới là tầm nhìn rộng mở; kính vỡ là cẩn thận hiểu lầm.',
      korea: 'Người Hàn cho rằng đeo kính mới là nhìn rõ tình hình, quyết định đúng; kính vỡ hay mất kính là suy nghĩ mình tin bị lung lay, dễ hiểu lầm — hãy kiểm tra lại; đeo kính râm là muốn che giấu lòng mình; cho người khác mượn kính là lời khuyên của mình có ích.',
      vietnam: 'Người Việt giải mơ thấy kính là sự sáng suốt nhìn rõ sự việc; kính mờ là việc chưa rõ ràng, đừng vội.',
      cases: [
        ['Mơ đeo kính mới', 'Tầm nhìn rộng, phán đoán tốt.'],
        ['Mơ kính vỡ', 'Kiểm tra lại để tránh hiểu lầm.'],
        ['Mơ đeo kính râm', 'Đừng che giấu lòng mình quá.'],
        ['Mơ cho mượn kính', 'Lời khuyên của bạn có ích.'],
      ],
    },
  },
  {
    slug: 'candle', category: 'situation', tone: 'mixed', emoji: '🕯️',
    ko: {
      name: '촛불 꿈', keywords: ['촛불', '초', '양초', '촛불 꿈', '촛불이 꺼지는 꿈'],
      summary: '촛불은 희망과 기도, 정성을 뜻합니다. 촛불이 밝게 타면 소원이 이루어지고, 꺼지면 건강과 마음을 돌보라는 꿈입니다.',
      korea: '촛불이 환하고 곧게 타오르면 정성이 통해 소원이 이루어지고 집안이 평안하다고 봅니다. 촛불을 새로 켜면 새로운 희망이나 인연이 시작되고, 촛불이 바람에 꺼지면 무리하지 말고 건강과 마음을 돌보라는 뜻입니다. 촛불을 여러 개 밝히면 경사와 축하할 일이 생깁니다.',
      vietnam: '베트남에서는 제단에 초(nến, 남부는 đèn cầy)와 향을 올려 조상께 기원합니다. 촛불 꿈은 조상의 보살핌과 정성을 뜻하며, 촛불이 꺼지면 집안 어른의 건강을 살피라는 뜻으로 봅니다.',
      cases: [
        ['촛불이 밝게 타는 꿈', '정성이 통해 소원이 이루어집니다.'],
        ['촛불을 새로 켜는 꿈', '새 희망이나 인연이 시작됩니다.'],
        ['촛불이 꺼지는 꿈', '무리하지 말고 건강을 돌보세요.'],
        ['촛불을 여러 개 밝히는 꿈', '경사와 축하할 일이 생깁니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy nến', keywords: ['nến', 'ngọn nến', 'đèn cầy', 'thắp nến', 'nến tắt'],
      summary: 'Nến là hy vọng, lời cầu nguyện và lòng thành. Nến cháy sáng là ước nguyện thành; nến tắt là nên chăm lo sức khỏe, tinh thần.',
      korea: 'Người Hàn cho rằng nến cháy sáng, thẳng là lòng thành được đáp, ước nguyện thành, nhà yên ổn; thắp nến mới là khởi đầu hy vọng hay duyên mới; nến bị gió thổi tắt là đừng cố quá, chăm sóc sức khỏe; thắp nhiều nến là có hỷ sự.',
      vietnam: 'Người Việt thắp nến (đèn cầy) và nhang trên bàn thờ để cầu tổ tiên. Mơ thấy nến là được ông bà che chở; nến tắt là nên hỏi thăm sức khỏe người lớn trong nhà.',
      cases: [
        ['Mơ nến cháy sáng', 'Lòng thành được đáp, ước nguyện thành.'],
        ['Mơ thắp nến mới', 'Hy vọng, duyên mới bắt đầu.'],
        ['Mơ nến tắt', 'Đừng cố quá, giữ sức khỏe.'],
        ['Mơ thắp nhiều nến', 'Có hỷ sự.'],
      ],
    },
  },
  {
    slug: 'book', category: 'situation', tone: 'good', emoji: '📚',
    ko: {
      name: '책 꿈', keywords: ['책', '책 읽는 꿈', '책 꿈', '도서관', '공부하는 꿈'],
      summary: '책은 지식과 지혜, 시험과 문서 운을 뜻합니다. 책을 받거나 읽으면 배움이 결실을 맺고 합격·계약에 좋은 길몽입니다.',
      korea: '누군가에게 책을 받으면 스승이나 귀인에게 가르침을 얻고, 시험이나 자격증에 합격한다고 봅니다. 책을 열심히 읽으면 지혜가 늘고 문서·계약 운이 좋아지며, 책이 가득한 도서관에 가면 공부운이 크게 열립니다. 책이 찢어지거나 젖으면 서류와 약속을 꼼꼼히 확인하라는 뜻입니다.',
      vietnam: '베트남은 문묘(Văn Miếu)에서 과거 급제를 기리는 등 학문을 귀하게 여깁니다. 책(sách) 꿈은 학업 성취와 승진, 지혜를 뜻하는 좋은 꿈입니다.',
      cases: [
        ['책을 선물받는 꿈', '가르침을 얻고 시험에 합격합니다.'],
        ['책을 열심히 읽는 꿈', '지혜가 늘고 문서운이 좋아집니다.'],
        ['도서관에 가는 꿈', '공부운이 크게 열립니다.'],
        ['책이 찢어지는 꿈', '서류와 약속을 꼼꼼히 확인하세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy sách', keywords: ['sách', 'quyển sách', 'đọc sách', 'thư viện'],
      summary: 'Sách là tri thức, trí tuệ và vận giấy tờ, thi cử. Được tặng sách hay đọc sách là việc học có kết quả — tốt cho thi cử, hợp đồng.',
      korea: 'Người Hàn cho rằng được ai đó tặng sách là nhận lời dạy từ thầy, quý nhân, thi đỗ; chăm chỉ đọc sách là thêm trí tuệ, vận giấy tờ hợp đồng tốt; vào thư viện đầy sách là vận học hành mở rộng; sách rách, ướt là kiểm tra kỹ giấy tờ, hẹn ước.',
      vietnam: 'Người Việt trọng chữ nghĩa — Văn Miếu còn bia tiến sĩ. Mơ thấy sách là học hành tấn tới, thăng tiến, sáng suốt.',
      cases: [
        ['Mơ được tặng sách', 'Có người dạy dỗ, thi đỗ.'],
        ['Mơ chăm chỉ đọc sách', 'Thêm trí tuệ, giấy tờ thuận lợi.'],
        ['Mơ vào thư viện', 'Vận học hành mở rộng.'],
        ['Mơ sách bị rách', 'Kiểm tra kỹ giấy tờ.'],
      ],
    },
  },
  {
    slug: 'hat', category: 'situation', tone: 'good', emoji: '🎩',
    ko: {
      name: '모자 꿈', keywords: ['모자', '갓', '모자 쓰는 꿈', '모자 꿈', '관모'],
      summary: '모자는 지위와 명예를 뜻합니다. 멋진 모자나 관을 쓰면 승진하거나 이름이 알려지는 길몽입니다.',
      korea: '옛날에는 관(冠)이나 갓을 쓰는 꿈을 벼슬에 오르는 꿈으로 풀었습니다. 지금도 새 모자를 쓰면 승진하거나 새 역할을 맡고, 남이 모자를 씌워 주면 윗사람의 추천을 받는다고 봅니다. 모자가 바람에 날아가면 체면이 상할 일을 조심하고, 모자를 벗으면 짐을 내려놓고 편해지는 꿈입니다.',
      vietnam: '베트남의 상징인 논라(nón lá, 원뿔 모양 삿갓)를 쓰는 꿈은 소박한 행복과 고향, 가족을 뜻합니다. 화려한 모자는 명예와 지위를 뜻합니다.',
      cases: [
        ['새 모자를 쓰는 꿈', '승진하거나 새 역할을 맡습니다.'],
        ['남이 모자를 씌워 주는 꿈', '윗사람의 추천을 받습니다.'],
        ['모자가 날아가는 꿈', '체면이 상할 일을 조심하세요.'],
        ['모자를 벗는 꿈', '짐을 내려놓고 편해집니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy mũ, nón', keywords: ['mũ', 'nón', 'nón lá', 'đội mũ', 'cái nón'],
      summary: 'Mũ là địa vị và danh dự. Đội mũ đẹp hay mũ quan là thăng chức, nổi tiếng.',
      korea: 'Ngày xưa người Hàn giải mơ đội mũ quan, mũ gat là sắp làm quan; nay đội mũ mới là thăng chức, nhận vai trò mới; được người khác đội mũ cho là được bề trên tiến cử; mũ bị gió thổi bay là cẩn thận mất mặt; bỏ mũ ra là trút gánh nặng, nhẹ nhõm.',
      vietnam: 'Mơ đội nón lá — biểu tượng Việt Nam — là hạnh phúc giản dị, quê hương, gia đình; mũ sang trọng là danh dự, địa vị.',
      cases: [
        ['Mơ đội mũ mới', 'Thăng chức, nhận vai trò mới.'],
        ['Mơ được người khác đội mũ cho', 'Được bề trên tiến cử.'],
        ['Mơ mũ bay mất', 'Cẩn thận chuyện mất mặt.'],
        ['Mơ cởi mũ', 'Trút gánh nặng, nhẹ nhõm.'],
      ],
    },
  },
  {
    slug: 'bus', category: 'situation', tone: 'mixed', emoji: '🚌',
    ko: {
      name: '버스 꿈', keywords: ['버스', '버스 타는 꿈', '버스 놓치는 꿈', '버스 꿈'],
      summary: '버스는 여러 사람과 함께 가는 인생의 방향을 뜻합니다. 버스를 제때 타면 흐름을 타고, 놓치면 기회를 챙기라는 꿈입니다.',
      korea: '버스에 제때 올라 자리에 앉으면 단체나 회사에서 내 자리를 찾고 일이 순조롭다고 봅니다. 버스를 놓치면 기회를 미루지 말라는 경고이고, 버스를 잘못 타면 가는 방향을 다시 점검하라는 뜻입니다. 만원 버스는 경쟁이 치열하니 차분히 실력을 쌓으라는 꿈입니다.',
      vietnam: '베트남에서 버스(xe buýt)나 장거리 버스(xe khách) 꿈은 이동과 변화를 뜻합니다. 버스를 놓치는 꿈은 결정을 망설이는 마음을 비춥니다.',
      cases: [
        ['버스에 타서 앉는 꿈', '내 자리를 찾고 일이 순조롭습니다.'],
        ['버스를 놓치는 꿈', '기회를 미루지 마세요.'],
        ['버스를 잘못 타는 꿈', '가는 방향을 다시 점검하세요.'],
        ['만원 버스 꿈', '경쟁이 치열합니다. 실력을 쌓으세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy xe buýt', keywords: ['xe buýt', 'xe khách', 'lỡ xe buýt', 'đi xe buýt'],
      summary: 'Xe buýt là hướng đi cuộc đời cùng nhiều người. Lên xe kịp là bắt nhịp; lỡ xe là nên nắm cơ hội.',
      korea: 'Người Hàn cho rằng lên xe buýt kịp và có chỗ ngồi là tìm được chỗ đứng trong tập thể, việc suôn sẻ; lỡ xe là đừng trì hoãn cơ hội; lên nhầm xe là xem lại hướng đi; xe chật kín người là cạnh tranh gay gắt, hãy bình tĩnh trau dồi.',
      vietnam: 'Người Việt giải mơ đi xe buýt, xe khách là đi lại, thay đổi; lỡ xe là đang do dự trước quyết định.',
      cases: [
        ['Mơ lên xe buýt có chỗ ngồi', 'Có chỗ đứng, việc suôn sẻ.'],
        ['Mơ lỡ xe buýt', 'Đừng trì hoãn cơ hội.'],
        ['Mơ đi nhầm xe', 'Xem lại hướng đi.'],
        ['Mơ xe buýt chật kín', 'Cạnh tranh gay gắt, hãy trau dồi.'],
      ],
    },
  },
  {
    slug: 'photo', category: 'situation', tone: 'mixed', emoji: '📷',
    ko: {
      name: '사진 꿈', keywords: ['사진', '사진 찍는 꿈', '사진 꿈', '영정 사진', '앨범'],
      summary: '사진은 추억과 기록, 남기고 싶은 순간을 뜻합니다. 함께 사진을 찍으면 관계가 깊어지고, 옛 사진은 과거를 정리하라는 꿈입니다.',
      korea: '사람들과 웃으며 사진을 찍으면 기념할 만한 좋은 일이 생기고 관계가 깊어진다고 봅니다. 옛 사진을 보면 지나간 인연이 다시 연락해 오거나 과거를 정리할 때라는 뜻입니다. 사진이 찢어지면 관계에 오해가 없게 하고, 영정 사진이 나오면 오히려 근심이 끝나고 장수한다는 반대 해몽이 있습니다.',
      vietnam: '베트남에서 사진(ảnh) 꿈은 추억과 그리움을 뜻합니다. 제단의 조상 사진을 보는 꿈은 조상이 보살펴 주니 제사를 챙기라는 뜻으로 봅니다.',
      cases: [
        ['함께 사진을 찍는 꿈', '기념할 일이 생기고 관계가 깊어집니다.'],
        ['옛 사진을 보는 꿈', '옛 인연의 연락이나 과거 정리의 때입니다.'],
        ['사진이 찢어지는 꿈', '관계에 오해가 없게 하세요.'],
        ['영정 사진을 보는 꿈', '근심이 끝나고 장수한다고 풉니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy chụp ảnh', keywords: ['chụp ảnh', 'bức ảnh', 'tấm ảnh', 'ảnh', 'ảnh thờ'],
      summary: 'Ảnh là kỷ niệm, lưu giữ khoảnh khắc. Chụp ảnh cùng ai là tình cảm sâu thêm; ảnh cũ là nên khép lại chuyện xưa.',
      korea: 'Người Hàn cho rằng cười vui chụp ảnh cùng mọi người là có chuyện đáng nhớ, quan hệ khăng khít; xem ảnh cũ là người xưa liên lạc hoặc lúc khép lại quá khứ; ảnh bị xé là tránh hiểu lầm; thấy ảnh thờ lại được giải ngược là hết lo âu, sống thọ.',
      vietnam: 'Người Việt giải mơ thấy ảnh là kỷ niệm, nhớ nhung; mơ thấy ảnh ông bà trên bàn thờ là tổ tiên phù hộ, nhắc chăm lo giỗ chạp.',
      cases: [
        ['Mơ chụp ảnh cùng mọi người', 'Có chuyện đáng nhớ, thêm gắn bó.'],
        ['Mơ xem ảnh cũ', 'Người xưa liên lạc, khép lại quá khứ.'],
        ['Mơ ảnh bị xé', 'Tránh hiểu lầm trong quan hệ.'],
        ['Mơ thấy ảnh thờ', 'Theo giải mộng Hàn: hết lo, sống thọ.'],
      ],
    },
  },
  {
    slug: 'cooking', category: 'situation', tone: 'good', emoji: '🍳',
    ko: {
      name: '요리하는 꿈', keywords: ['요리', '요리하는 꿈', '밥 짓는 꿈', '음식 만드는 꿈', '부엌'],
      summary: '요리는 준비와 정성, 결실을 뜻합니다. 맛있는 음식을 만들어 나누면 노력이 인정받고 사람이 모이는 길몽입니다.',
      korea: '정성껏 요리해 사람들과 나누면 내가 준비한 일이 좋은 평가를 받고 주변에 사람이 모인다고 봅니다. 큰 솥에 밥을 지으면 집안 살림이 넉넉해지고, 음식을 태우면 서두르다 일을 그르치지 않도록 조심하라는 뜻입니다. 부엌이 깨끗하면 집안이 평안합니다.',
      vietnam: '베트남에서 요리하는 꿈(nấu ăn)은 가정의 화목과 풍요를 뜻합니다. 설 음식(반쯩 등)을 만드는 꿈은 가족이 모이고 복이 드는 좋은 꿈입니다.',
      cases: [
        ['음식을 만들어 나누는 꿈', '노력이 인정받고 사람이 모입니다.'],
        ['큰 솥에 밥을 짓는 꿈', '살림이 넉넉해집니다.'],
        ['음식을 태우는 꿈', '서두르지 말고 차근차근 하세요.'],
        ['깨끗한 부엌 꿈', '집안이 평안합니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy nấu ăn', keywords: ['nấu ăn', 'nấu cơm', 'nấu cỗ', 'nhà bếp', 'gói bánh chưng'],
      summary: 'Nấu ăn là chuẩn bị, tâm huyết và thành quả. Nấu món ngon rồi chia cho mọi người là được ghi nhận, người tụ về.',
      korea: 'Người Hàn cho rằng nấu ăn chu đáo rồi chia cho mọi người là việc mình chuẩn bị được đánh giá tốt, nhiều người tụ lại; nấu nồi cơm lớn là nhà cửa sung túc; làm cháy đồ ăn là đừng vội mà hỏng việc; bếp sạch sẽ là gia đạo yên ổn.',
      vietnam: 'Người Việt giải mơ nấu ăn là gia đình hòa thuận, no đủ; mơ gói bánh chưng, nấu cỗ Tết là cả nhà sum họp, phúc vào nhà.',
      cases: [
        ['Mơ nấu món ngon chia mọi người', 'Được ghi nhận, người tụ về.'],
        ['Mơ nấu nồi cơm lớn', 'Nhà cửa sung túc.'],
        ['Mơ làm cháy đồ ăn', 'Đừng vội, làm từng bước.'],
        ['Mơ nhà bếp sạch sẽ', 'Gia đạo yên ổn.'],
      ],
    },
  },
  {
    slug: 'tattoo', category: 'situation', tone: 'mixed', emoji: '🖋️',
    ko: {
      name: '문신 꿈', keywords: ['문신', '타투', '문신 꿈', '문신하는 꿈'],
      summary: '문신은 지워지지 않는 결심과 변화, 오래 남을 사건을 뜻합니다. 마음에 드는 문신은 새 출발, 원치 않는 문신은 구설을 조심하라는 꿈입니다.',
      korea: '마음에 드는 문신을 새기면 굳은 결심으로 새 출발을 하거나 잊지 못할 좋은 일이 생긴다고 봅니다. 원하지 않는 문신이 생기면 남의 말에 낙인찍히지 않도록 언행을 조심하고, 문신을 지우면 지난 실수를 정리하고 새로워진다는 뜻입니다. 용이나 호랑이 문신은 힘과 권위를 얻는 꿈으로 풉니다.',
      vietnam: '베트남 고대 락비엣(Lạc Việt) 사람들은 물속 괴물을 피하려 몸에 문신을 했다는 전설이 있습니다. 문신(hình xăm) 꿈은 자기 정체성과 보호를 뜻합니다.',
      cases: [
        ['마음에 드는 문신을 새기는 꿈', '굳은 결심으로 새 출발합니다.'],
        ['원치 않는 문신이 생기는 꿈', '언행을 조심해 구설을 피하세요.'],
        ['문신을 지우는 꿈', '지난 실수를 정리하고 새로워집니다.'],
        ['용·호랑이 문신 꿈', '힘과 권위를 얻습니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy hình xăm', keywords: ['hình xăm', 'xăm hình', 'đi xăm', 'xóa xăm'],
      summary: 'Hình xăm là quyết tâm khó phai, sự thay đổi và chuyện nhớ lâu. Hình xăm ưng ý là khởi đầu mới; hình xăm không muốn là coi chừng thị phi.',
      korea: 'Người Hàn cho rằng xăm hình ưng ý là quyết tâm bắt đầu lại hoặc có chuyện vui khó quên; bị xăm hình không mong muốn là cẩn thận lời ăn tiếng nói kẻo bị “dán nhãn”; xóa hình xăm là khép lại lỗi cũ, làm mới mình; xăm rồng hay hổ là có sức mạnh, uy quyền.',
      vietnam: 'Truyền thuyết kể người Lạc Việt xưa xăm mình để tránh thủy quái. Mơ thấy hình xăm là bản sắc, sự che chở cho chính mình.',
      cases: [
        ['Mơ xăm hình ưng ý', 'Quyết tâm khởi đầu mới.'],
        ['Mơ bị xăm hình không muốn', 'Giữ lời ăn tiếng nói.'],
        ['Mơ xóa hình xăm', 'Khép lại lỗi cũ, làm mới mình.'],
        ['Mơ xăm rồng, hổ', 'Có sức mạnh, uy quyền.'],
      ],
    },
  },
  {
    slug: 'travel', category: 'situation', tone: 'good', emoji: '🧳',
    ko: {
      name: '여행 꿈', keywords: ['여행', '여행 가는 꿈', '해외여행', '여행 꿈', '짐 싸는 꿈'],
      summary: '여행은 변화와 새 출발, 쉼을 뜻합니다. 즐겁게 여행하면 새로운 환경에서 기회를 얻고, 짐을 못 싸면 준비를 서두르라는 꿈입니다.',
      korea: '즐겁게 여행을 떠나면 이사, 이직, 새 인연 등 환경이 바뀌며 좋은 기회를 만난다고 봅니다. 해외로 가면 시야가 넓어지고 먼 곳과의 일이 생기며, 짐을 싸다 시간이 모자라면 준비가 덜 되었으니 서두르라는 뜻입니다. 여행지에서 길을 잃으면 계획을 다시 세우라는 꿈입니다.',
      vietnam: '베트남에서 여행(du lịch) 꿈은 운이 바뀌고 새로운 기회가 온다는 뜻입니다. 가족과 함께하는 여행은 화목을, 혼자 떠나는 여행은 자기 성장을 뜻합니다.',
      cases: [
        ['즐겁게 여행을 떠나는 꿈', '환경이 바뀌며 좋은 기회를 만납니다.'],
        ['해외여행 꿈', '시야가 넓어지고 먼 곳과의 일이 생깁니다.'],
        ['짐을 다 못 싸는 꿈', '준비를 서두르세요.'],
        ['여행지에서 길을 잃는 꿈', '계획을 다시 세우세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đi du lịch', keywords: ['du lịch', 'đi du lịch', 'đi nước ngoài', 'xếp hành lý', 'chuyến đi'],
      summary: 'Du lịch là thay đổi, khởi đầu mới và nghỉ ngơi. Đi chơi vui vẻ là gặp cơ hội ở môi trường mới; không kịp xếp đồ là nên chuẩn bị gấp.',
      korea: 'Người Hàn cho rằng vui vẻ lên đường du lịch là môi trường thay đổi — chuyển nhà, đổi việc, duyên mới — kèm cơ hội tốt; đi nước ngoài là mở rộng tầm nhìn, có việc liên quan nơi xa; xếp hành lý không kịp là chưa chuẩn bị đủ; lạc đường nơi du lịch là nên lập lại kế hoạch.',
      vietnam: 'Người Việt giải mơ đi du lịch là vận đổi, cơ hội mới; đi cùng gia đình là hòa thuận, đi một mình là trưởng thành.',
      cases: [
        ['Mơ vui vẻ đi du lịch', 'Gặp cơ hội ở môi trường mới.'],
        ['Mơ đi nước ngoài', 'Tầm nhìn rộng, có việc nơi xa.'],
        ['Mơ xếp hành lý không kịp', 'Cần chuẩn bị gấp.'],
        ['Mơ lạc đường khi du lịch', 'Lập lại kế hoạch.'],
      ],
    },
  },
  {
    slug: 'needle', category: 'situation', tone: 'mixed', emoji: '🪡',
    ko: {
      name: '바늘 꿈', keywords: ['바늘', '바느질', '바늘에 찔리는 꿈', '실', '주사'],
      summary: '바늘은 섬세한 일과 관계를 이어 주는 힘을 뜻합니다. 바느질을 하면 틀어진 관계를 꿰매고, 바늘에 찔리면 날카로운 말을 조심하라는 꿈입니다.',
      korea: '바느질로 옷을 깁으면 틀어진 관계가 회복되고 꼼꼼한 일솜씨가 인정받는다고 봅니다. 바늘에 찔리면 가까운 사람의 날카로운 말에 상처받을 수 있으니 거리를 두고, 바늘을 잃어버리면 작은 실수를 조심하라는 뜻입니다. 바늘에 실을 한 번에 꿰면 어려운 일이 단번에 풀립니다.',
      vietnam: '베트남에서 바늘과 실(kim chỉ) 꿈은 인연과 정성을 뜻합니다. "바늘과 실처럼" 붙어 다니는 단짝이나 부부의 정을 뜻하기도 합니다.',
      cases: [
        ['바느질하는 꿈', '틀어진 관계가 회복됩니다.'],
        ['바늘에 찔리는 꿈', '날카로운 말에 상처받지 않게 거리를 두세요.'],
        ['바늘을 잃어버리는 꿈', '작은 실수를 조심하세요.'],
        ['바늘에 실을 한 번에 꿰는 꿈', '어려운 일이 단번에 풀립니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy kim chỉ', keywords: ['kim chỉ', 'cây kim', 'kim khâu', 'khâu vá', 'bị kim đâm'],
      summary: 'Kim là việc tỉ mỉ và sức nối kết các mối quan hệ. Khâu vá là hàn gắn quan hệ; bị kim đâm là cẩn thận lời nói sắc bén.',
      korea: 'Người Hàn cho rằng khâu vá quần áo là quan hệ rạn nứt được hàn gắn, sự tỉ mỉ được công nhận; bị kim đâm là có thể tổn thương vì lời nói sắc của người gần; làm mất kim là cẩn thận lỗi nhỏ; xỏ kim một lần là được là việc khó gỡ được ngay.',
      vietnam: 'Người Việt giải mơ thấy kim chỉ là duyên nợ và sự chu đáo; “như kim với chỉ” còn là đôi bạn thân hay vợ chồng gắn bó.',
      cases: [
        ['Mơ khâu vá', 'Quan hệ được hàn gắn.'],
        ['Mơ bị kim đâm', 'Tránh xa lời nói làm tổn thương.'],
        ['Mơ làm mất kim', 'Cẩn thận lỗi nhỏ.'],
        ['Mơ xỏ kim một lần là được', 'Việc khó được gỡ ngay.'],
      ],
    },
  },
  {
    slug: 'fireworks', category: 'situation', tone: 'good', emoji: '🎆',
    ko: {
      name: '불꽃놀이 꿈', keywords: ['불꽃놀이', '폭죽', '불꽃 축제', '불꽃놀이 꿈'],
      summary: '불꽃놀이는 축하와 기쁨, 이름이 알려지는 순간을 뜻합니다. 다만 화려함은 잠깐이니 성과를 잘 지키라는 뜻도 담겨 있습니다.',
      korea: '밤하늘에 불꽃이 화려하게 터지면 축하할 일과 경사가 생기고, 내 노력이 많은 사람에게 알려진다고 봅니다. 사랑하는 사람과 불꽃놀이를 보면 관계가 뜨거워지고, 폭죽이 가까이서 터져 놀라면 들뜬 마음에 실수하지 않도록 조심하라는 뜻입니다. 불꽃이 금방 꺼지면 반짝 성과를 꾸준함으로 이어 가세요.',
      vietnam: '베트남에서 불꽃놀이(pháo hoa)는 설 전야(giao thừa)의 상징입니다. 불꽃놀이 꿈은 새해의 행운, 새로운 시작, 기쁜 소식을 뜻하는 좋은 꿈입니다.',
      cases: [
        ['화려한 불꽃놀이를 보는 꿈', '경사가 생기고 이름이 알려집니다.'],
        ['연인과 불꽃놀이를 보는 꿈', '관계가 뜨거워집니다.'],
        ['폭죽이 가까이서 터지는 꿈', '들뜬 마음에 실수하지 마세요.'],
        ['불꽃이 금방 꺼지는 꿈', '반짝 성과를 꾸준함으로 이어 가세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy pháo hoa', keywords: ['pháo hoa', 'bắn pháo hoa', 'pháo', 'giao thừa'],
      summary: 'Pháo hoa là chúc mừng, niềm vui và lúc được nhiều người biết đến. Nhưng rực rỡ thì ngắn ngủi — hãy giữ thành quả.',
      korea: 'Người Hàn cho rằng pháo hoa rực rỡ trên trời đêm là có hỷ sự, công sức được nhiều người biết; ngắm pháo hoa cùng người thương là tình cảm nồng nhiệt; pháo nổ sát bên làm giật mình là cẩn thận phấn khích quá mà sai; pháo hoa tắt nhanh là hãy biến thành công nhất thời thành bền bỉ.',
      vietnam: 'Với người Việt, pháo hoa là khoảnh khắc giao thừa. Mơ thấy pháo hoa là may mắn năm mới, khởi đầu mới, tin vui.',
      cases: [
        ['Mơ ngắm pháo hoa rực rỡ', 'Có hỷ sự, được biết đến.'],
        ['Mơ xem pháo hoa cùng người yêu', 'Tình cảm nồng nhiệt.'],
        ['Mơ pháo nổ sát bên', 'Đừng phấn khích quá mà sai.'],
        ['Mơ pháo hoa tắt nhanh', 'Duy trì thành công bằng sự bền bỉ.'],
      ],
    },
  },
  {
    slug: 'shopping', category: 'situation', tone: 'mixed', emoji: '🛍️',
    ko: {
      name: '쇼핑하는 꿈', keywords: ['쇼핑', '쇼핑하는 꿈', '물건 사는 꿈', '백화점', '마트'],
      summary: '쇼핑은 원하는 것과 선택을 뜻합니다. 마음에 드는 물건을 사면 바라던 것을 얻고, 돈이 모자라면 지출을 점검하라는 꿈입니다.',
      korea: '마음에 꼭 드는 물건을 사면 바라던 일이나 인연을 손에 넣는다고 봅니다. 백화점에서 고르기만 하고 못 사면 선택을 앞두고 망설이는 마음이니 우선순위를 정하라는 뜻이고, 계산할 때 돈이 모자라면 실제 지출을 점검하라는 경고입니다. 남에게 줄 선물을 고르면 인간관계가 좋아집니다.',
      vietnam: '베트남에서 물건을 사는 꿈(mua sắm)은 새로운 기회와 욕구를 뜻하며, 돈을 많이 쓰는 꿈은 실제로 절약하라는 반대 의미로 풀기도 합니다.',
      cases: [
        ['마음에 드는 물건을 사는 꿈', '바라던 것을 손에 넣습니다.'],
        ['고르기만 하고 못 사는 꿈', '우선순위를 정하세요.'],
        ['계산할 때 돈이 모자란 꿈', '지출을 점검하세요.'],
        ['선물을 고르는 꿈', '인간관계가 좋아집니다.'],
      ],
    },
    vi: {
      name: 'Mơ thấy đi mua sắm', keywords: ['mua sắm', 'đi mua sắm', 'trung tâm thương mại', 'siêu thị', 'mua đồ'],
      summary: 'Mua sắm là mong muốn và lựa chọn. Mua được món ưng ý là đạt điều mong; thiếu tiền khi trả là nên xem lại chi tiêu.',
      korea: 'Người Hàn cho rằng mua được món thật ưng ý là có được việc hay duyên mình mong; chỉ ngắm mà không mua được là đang do dự trước lựa chọn — hãy xếp thứ tự ưu tiên; thiếu tiền lúc thanh toán là nhắc kiểm tra chi tiêu thật; chọn quà cho người khác là quan hệ tốt lên.',
      vietnam: 'Người Việt giải mơ mua sắm là cơ hội mới, mong muốn; mơ tiêu nhiều tiền lại được giải ngược là nên tiết kiệm.',
      cases: [
        ['Mơ mua được món ưng ý', 'Đạt điều mong muốn.'],
        ['Mơ chỉ ngắm không mua', 'Xếp thứ tự ưu tiên.'],
        ['Mơ thiếu tiền khi trả', 'Kiểm tra chi tiêu.'],
        ['Mơ chọn quà cho người khác', 'Quan hệ tốt lên.'],
      ],
    },
  },
  {
    slug: 'award', category: 'situation', tone: 'good', emoji: '🏆',
    ko: {
      name: '상 받는 꿈', keywords: ['상 받는 꿈', '상장', '트로피', '메달', '시상식', '1등 하는 꿈'],
      summary: '상을 받는 꿈은 노력이 인정받고 명예가 오르는 길몽입니다. 1등을 하면 경쟁에서 앞서고 좋은 소식이 옵니다.',
      korea: '무대에서 상장이나 트로피를 받으면 그동안의 노력이 인정받아 승진, 합격, 수상 같은 좋은 일이 생긴다고 봅니다. 금메달을 목에 걸면 경쟁에서 앞서고, 가족이 상을 받으면 집안에 경사가 생깁니다. 상을 받았는데 기쁘지 않으면 남의 평가보다 내가 원하는 것을 돌아보라는 뜻입니다.',
      vietnam: '베트남에서 상을 받는 꿈(nhận giải thưởng)은 명예와 성취, 직장 내 인정을 뜻하는 좋은 꿈입니다.',
      cases: [
        ['상장이나 트로피를 받는 꿈', '노력이 인정받고 승진·합격합니다.'],
        ['금메달을 거는 꿈', '경쟁에서 앞섭니다.'],
        ['가족이 상을 받는 꿈', '집안에 경사가 생깁니다.'],
        ['상을 받아도 기쁘지 않은 꿈', '내가 진짜 원하는 것을 돌아보세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy nhận giải thưởng', keywords: ['giải thưởng', 'nhận giải', 'huy chương', 'cúp', 'đạt giải nhất'],
      summary: 'Mơ nhận giải là nỗ lực được công nhận, danh dự tăng. Đạt giải nhất là vượt lên trong cạnh tranh, có tin vui.',
      korea: 'Người Hàn cho rằng lên sân khấu nhận bằng khen hay cúp là công sức được ghi nhận — thăng chức, thi đỗ, đoạt giải; đeo huy chương vàng là vượt lên trong cạnh tranh; người nhà nhận giải là nhà có hỷ sự; nhận giải mà không vui là nên xem điều mình thực sự muốn thay vì đánh giá của người khác.',
      vietnam: 'Người Việt giải mơ nhận giải thưởng là danh dự, thành tựu, được công nhận nơi làm việc.',
      cases: [
        ['Mơ nhận bằng khen, cúp', 'Được ghi nhận, thăng chức, thi đỗ.'],
        ['Mơ đeo huy chương vàng', 'Vượt lên trong cạnh tranh.'],
        ['Mơ người nhà nhận giải', 'Nhà có hỷ sự.'],
        ['Mơ nhận giải mà không vui', 'Xem lại điều mình thật sự muốn.'],
      ],
    },
  },
  {
    slug: 'motorbike', category: 'situation', tone: 'mixed', emoji: '🛵',
    ko: {
      name: '오토바이 꿈', keywords: ['오토바이', '스쿠터', '오토바이 타는 꿈', '오토바이 사고'],
      summary: '오토바이는 자유와 속도, 스스로 개척하는 길을 뜻합니다. 시원하게 달리면 일이 빠르게 풀리고, 넘어지면 속도를 줄이라는 꿈입니다.',
      korea: '오토바이를 타고 시원하게 달리면 스스로 길을 개척해 일이 빠르게 진척된다고 봅니다. 누군가를 뒤에 태우면 그 사람과 운명을 함께할 일이 생기고, 오토바이가 넘어지거나 사고가 나면 서두르다 다치지 않게 속도를 줄이라는 경고입니다. 오토바이를 잃어버리면 일상의 기반을 잘 챙기라는 뜻입니다.',
      vietnam: '베트남에서 오토바이(xe máy)는 생활 그 자체라 꿈에 자주 나옵니다. 새 오토바이를 사면 생활이 나아지고 일이 순조로우며, 오토바이를 잃어버리는 꿈은 재산 손실이나 일이 막히는 것을 조심하라는 뜻으로 봅니다.',
      cases: [
        ['오토바이로 시원하게 달리는 꿈', '일이 빠르게 풀립니다.'],
        ['누군가를 뒤에 태우는 꿈', '그 사람과 함께할 일이 생깁니다.'],
        ['오토바이가 넘어지는 꿈', '서두르지 말고 속도를 줄이세요.'],
        ['오토바이를 잃어버리는 꿈', '생활의 기반을 잘 챙기세요.'],
      ],
    },
    vi: {
      name: 'Mơ thấy xe máy', keywords: ['xe máy', 'đi xe máy', 'mất xe máy', 'ngã xe máy', 'mua xe máy'],
      summary: 'Xe máy là tự do, tốc độ và con đường tự mở. Phóng xe thoải mái là việc mau xong; ngã xe là nên giảm tốc.',
      korea: 'Người Hàn cho rằng phóng xe máy thoải mái là tự mở đường, việc tiến triển nhanh; chở ai phía sau là sẽ gắn bó, cùng làm việc với người đó; ngã xe, tai nạn là vội quá dễ hỏng việc — giảm tốc; mất xe là giữ gìn nền tảng cuộc sống thường ngày.',
      vietnam: 'Ở Việt Nam xe máy là đời sống nên rất hay xuất hiện trong mơ. Mơ mua xe máy mới là cuộc sống khá lên, việc thuận lợi; mơ mất xe máy là cẩn thận hao tài, công việc trắc trở.',
      cases: [
        ['Mơ phóng xe máy thoải mái', 'Việc tiến triển nhanh.'],
        ['Mơ chở ai sau xe', 'Sẽ gắn bó với người ấy.'],
        ['Mơ ngã xe máy', 'Đừng vội, giảm tốc.'],
        ['Mơ mất xe máy', 'Giữ gìn tài sản, nền tảng.'],
      ],
    },
  },
];
