"""Builds the 원획 (KangXi-radical) stroke tables used for Korean name analysis.

Source: Unihan (kRSKangXi, kHangul) as packaged in the npm module cjk-unihan:
    npm pack cjk-unihan && tar xzf cjk-unihan-*.tgz
    python3 scripts/gen-strokes.py package/data/unihan.db

원획 = full stroke count of the KangXi radical (氵→水 4, 艹→艸 6, 阝→阜 8 / 邑 7 …) + residual strokes.
Numerals follow naming custom (四 4, 五 5 … 十 10).
"""
import json, os, re, sqlite3, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANDS = [(6, 1), (29, 2), (60, 3), (94, 4), (117, 5), (146, 6), (166, 7), (175, 8), (186, 9), (194, 10),
         (200, 11), (204, 12), (208, 13), (210, 14), (211, 15), (213, 16), (214, 17)]
NUMERALS = {'一': 1, '二': 2, '三': 3, '四': 4, '五': 5, '六': 6, '七': 7, '八': 8, '九': 9, '十': 10}


def radical_strokes(n):
    for hi, s in BANDS:
        if n <= hi:
            return s


def won(rs):
    rad, res = rs.split()[0].split('.')
    return radical_strokes(int(rad.rstrip("'"))) + int(res)


db = sqlite3.connect(sys.argv[1])
rows = db.execute("select character, kRSKangXi, kHangul from unihan where kHangul != '' and kRSKangXi is not null").fetchall()
table = {}
for ch, rs, hangul in rows:
    if 0x4E00 <= ord(ch) <= 0x9FFF and rs.strip():
        table[ch] = (NUMERALS.get(ch, won(rs)), hangul.split()[0])

# Small table: every hanja that appears in the name data files (bundled with the page).
used = set()
for f in ['src/content/koNames.ts', 'src/content/hanja.ts', 'src/engine/naming.ts']:
    used |= set(re.findall(r'[一-鿿]', open(os.path.join(ROOT, f), encoding='utf-8').read()))
for ch in used - set(table):
    r = db.execute("select kRSKangXi from unihan where character = ?", (ch,)).fetchone()
    if r and r[0] and r[0].strip():
        table[ch] = (NUMERALS.get(ch, won(r[0])), '')
small = {c: table[c][0] for c in sorted(used) if c in table}
missing = sorted(used - set(small))
with open(os.path.join(ROOT, 'src/content/nameStrokes.json'), 'w', encoding='utf-8') as fh:
    json.dump(small, fh, ensure_ascii=False, separators=(',', ':'))

# Full table (lazy-loaded): "字14서" entries joined by commas.
big = ','.join(f'{c}{s}{h}' for c, (s, h) in sorted(table.items()) if h)
with open(os.path.join(ROOT, 'src/content/strokeTable.ts'), 'w', encoding='utf-8') as fh:
    fh.write('// Generated by scripts/gen-strokes.py from Unihan — 원획 stroke count and Korean reading per hanja.\n')
    fh.write(f'export const STROKE_TABLE = {json.dumps(big, ensure_ascii=False)};\n')
print(len(small), 'name chars;', len(table), 'in full table; missing:', ''.join(missing))
