// Heavenly stems (천간 / Thiên can), earthly branches (지지 / Địa chi), five elements (오행 / Ngũ hành).

export const STEM_HANJA = ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸'];
export const BRANCH_HANJA = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];

/** 0 wood, 1 fire, 2 earth, 3 metal, 4 water */
export type Element = 0 | 1 | 2 | 3 | 4;
export const ELEMENT_HANJA = ['木', '火', '土', '金', '水'];

export const stemElement = (s: number): Element => Math.floor(s / 2) as Element;
/** true = 양(陽) */
export const stemYang = (s: number) => s % 2 === 0;

const BRANCH_ELEMENT: Element[] = [4, 2, 0, 0, 2, 1, 1, 2, 3, 3, 2, 4];
export const branchElement = (b: number): Element => BRANCH_ELEMENT[b];
export const branchYang = (b: number) => b % 2 === 0;

/** 지장간 (hidden stems), main qi last */
export const HIDDEN_STEMS: number[][] = [
  [8, 9], [9, 7, 5], [4, 2, 0], [0, 1], [1, 9, 4], [4, 6, 2],
  [2, 5, 3], [3, 1, 5], [4, 8, 6], [6, 7], [7, 3, 4], [4, 0, 8],
];
export const mainHiddenStem = (b: number) => HIDDEN_STEMS[b][HIDDEN_STEMS[b].length - 1];

/** Index 0..59 in the sexagenary cycle → stem/branch */
export const cycleStem = (i: number) => ((i % 10) + 10) % 10;
export const cycleBranch = (i: number) => ((i % 12) + 12) % 12;
/** stem/branch → index 0..59 (assumes matching parity) */
export const cycleIndex = (stem: number, branch: number) => (6 * stem - 5 * branch + 60) % 60;

export const mod = (n: number, m: number) => ((n % m) + m) % m;

/** Day pillar cycle index from JDN (2000-01-01 = 戊午 = 54). */
export const dayCycle = (jdn: number) => mod(jdn + 49, 60);

/** Year pillar cycle index for a 사주 year (starting at 입춘). 1984 = 甲子. */
export const yearCycle = (year: number) => mod(year - 1984, 60);

export type TenGod =
  | 'bijian' | 'jiecai' | 'shishen' | 'shangguan' | 'piancai'
  | 'zhengcai' | 'qisha' | 'zhengguan' | 'pianyin' | 'zhengyin';

const TEN_GODS: TenGod[][] = [
  ['bijian', 'jiecai'],
  ['shishen', 'shangguan'],
  ['piancai', 'zhengcai'],
  ['qisha', 'zhengguan'],
  ['pianyin', 'zhengyin'],
];

/** 십신 of `other` stem relative to day master `day`. */
export function tenGod(day: number, other: number): TenGod {
  const rel = mod(stemElement(other) - stemElement(day), 5);
  return TEN_GODS[rel][stemYang(other) === stemYang(day) ? 0 : 1];
}

export const TWELVE_STAGES = ['長生', '沐浴', '冠帶', '臨官', '帝旺', '衰', '病', '死', '墓', '絶', '胎', '養'];
const STAGE_START = [11, 6, 2, 9, 2, 9, 5, 0, 8, 3];

/** 12운성 index of stem in branch */
export function twelveStage(stem: number, branch: number): number {
  const start = STAGE_START[stem];
  return stemYang(stem) ? mod(branch - start, 12) : mod(start - branch, 12);
}

// Branch relations
const SIX_HARMONY = [1, 0, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2];
export const isSixHarmony = (a: number, b: number) => SIX_HARMONY[a] === b;
export const isClash = (a: number, b: number) => mod(a - b, 12) === 6;
export const isThreeHarmony = (a: number, b: number) => a !== b && mod(a - b, 4) === 0;
const HARM = [7, 6, 5, 4, 3, 2, 1, 0, 11, 10, 9, 8];
export const isHarm = (a: number, b: number) => HARM[a] === b;
const PUNISH: Record<number, number[]> = {
  2: [5, 8], 5: [2, 8], 8: [2, 5], 1: [10, 7], 10: [1, 7], 7: [1, 10], 0: [3], 3: [0],
  4: [4], 6: [6], 9: [9], 11: [11],
};
export const isPunish = (a: number, b: number) => (PUNISH[a] ?? []).includes(b);

/** Element that generates `e` (인성 element) */
export const generatorOf = (e: Element): Element => mod(e - 1, 5) as Element;
/** Element generated by `e` */
export const generatedBy = (e: Element): Element => mod(e + 1, 5) as Element;
